- application/controllers/board.js
- application/controllers/index.js
- application/controllers/users.js
- application/index.js
- application/public/css/main.css
- application/views/homepage.ejs
- application/views/layout.ejs
- application/views/login.ejs
- application/views/register.ejs
- package-lock.json
- package.json
This PR adds and configures the dependencies `ejs` and `express-ejs-layouts`.
These two libraries are primarily used to simply UI ("User Interface") operations such as passing variables when rendering a view (courtesy of EJS), and much, much more.
This PR also adds the views, `homepage`, `login`, `register`, as well as configures the routes that will render those views.
> Configure User Interface

- application/controllers/users.js
- application/index.js
- application/models/user.js
- application/services/databaseService.js
- application/services/userService.js
- application/views/register.ejs
- package-lock.json
- package.json
- test/models/user.spec.js
- test/services/databaseService.spec.js
- test/services/userService.spec.js
In this PR, the cloud database provider `mongoDB` was chosen to be the database provider.
To interact with this database, the dependency `mongoose` is used, which simplifies the `CREATE`/`READ`/`UPDATE`/`DELETE` interactions.
> Setup Mongoose Database Connections

- application/controllers/users.js
- application/views/layout.ejs
- application/views/register.ejs
- package-lock.json
- package.json
In this PR, the endpoint that handles registering a user during signup was refactored and validation was added.
After this PR a signedup user has their information validated against basic rules (i.e. password length, unique email) and their password is encrypted prior to being added to the database utilizing a library added in this PR called `bcryptjs`.
This registered user is then saved to a mongo database.
Later PRs will be opened to deal with the sign-in/authentication portions
> Handle User Registration

- application/controllers/users.js
- application/views/login.ejs
- package-lock.json
- package.json
This PR adds login functionality that determines if a given combination of email/password is valid.
A successfully logged-in user is provided a JWT ("Json Web Token") which can be used to easily authenticate users on following requests.
> Feature: User Login

- application/controllers/users.js
- application/views/changePassword.ejs
This PR offers the ability for a user to change their password.
> Feature: Change Password

- application/controllers/users.js
- application/index.js
- application/middleware/authorize.js
- application/views/login.ejs
- application/views/profile.ejs
- package-lock.json
- package.json
This PR introduces a User Profile Page.
In order to welcome a signed-in user, that user must log in and that the User's information is stored in the session via a JWT.
> User Profile Page

- package-lock.json
- package.json
Once this repo was hosted up on Heroku, a dependency install error was encountered.
It seems that the dependency `mongodb-memory-server` was installed as a devDependency, but was used in live code (outside of test files).
The fix for this was to move it in as a real dependency instead
> Fix Broken CI/CD Pipeline V2 (lol)

- package.json
The Node engine specified was incorrect and caused build failures.
This PR updates the versions of Node/NPM listed in `package.json` to be exactly what I have installed locally
> Fix Incorrectly Specified Node Engine

- application/controllers/users.js
- application/index.js
- application/views/changePassword.ejs
- application/views/login.ejs
- application/views/profile.ejs
- application/views/register.ejs
This PR tweaks the Login/Register/Change Password flow and also refactors the Profile page.
After this PR, JWT tokens are stored and retrieved in a repeatable, security-safe manner (httponly cookies).
Endpoints that should be only accessible to signed-in users (aka profile pages) are now protected via authentication middleware functions.
> Login/Registration/Change-Password Flow Updates

- application/controllers/users.js
- application/index.js
- application/views/flashMessages.ejs
- application/views/layout.ejs
- package-lock.json
- package.json
Imagine a scenario where you tryped in an invalid username/password when logging into a platform, ideally, it would be nice to see a message informing you about this.
This PR introduces flash messages, which are configured to be used on any HTML page on this website to inform the user of any ERRORS or ALERTS that occurred during any request.
> Feature: Flash Messages

- application/controllers/users.js
- application/middleware/authorize.js
- application/views/profile.ejs
- test/middleware/authorize.spec.js
This PR adds a logout button to a users profile page and configures a POST /logout route which clears the users JWT token (aka ends their login) and redirects them to the homepage.
> Feature: Logout

- application/controllers/users.js
- application/services/emailService.js
- application/views/forgotPassword.ejs
- application/views/login.ejs
- application/views/resetPassword.ejs
- package-lock.json
- package.json
- test/services/databaseService.spec.js
- test/services/emailService.spec.js
- test/services/userService.spec.js
This PR adds the functionality required for a user to reset the password on their account in the event that they forgot the original password.
After this PR, a user is able to enter their email address associated to their account and then they will receive an email with a link that they may visit in order to set a new password onto that account.
> Feature: "Forgot My Password" Functionality

- application/models/recipe.js
- test/models/recipe.spec.js
This PR introduces a model named `Recipe` and defines the attributes which must be set onto that model before it can be saved to the database.
> Introduce MongoDB Model named `Recipe`

- application/controllers/recipeController.js
- application/views/allRecipes.ejs
A user has the ability to create a `recipe` by filling out a form.
All recipes can be viewed in a list in the form of a HTML table.
One of the columns on that table is an `author` attribute.
Previously this author column simply displayed a non-informational string.
After this PR, that column successfully displays the email for the user who created that `recipe`.
> Feature: Populate Email Address Instead of Database UUID Identifier

- application/controllers/recipeController.js
- application/views/allRecipes.ejs
- application/views/updateRecipe.ejs
Previously, users had the ability to create `recipes` but they lacked the ability to `UPDATE` these recipes once they were created.
This PR provides a user interface that allows users to do this.
> User has ability to edit any `recipe`
> User can fill out form and upon submitting it, the `recipe` will be updated in the database
> Feature: Add UPDATE Functionality to RECIPES

- application/controllers/recipeController.js
I'm dumb and forgot to add a POST `/update` endpoint in #22 
This PR fixes that mistake and adds the endpoint such that when form submission occurs, the `recipe` table is updated accordingly
> Fix: Add Missing `/update` Endpoint

- application/controllers/finishController.js
- application/controllers/machineController.js
- application/controllers/materialController.js
- application/controllers/recipeController.js
- application/views/updateFinish.ejs
- application/views/updateMachine.ejs
- application/views/updateMaterial.ejs
- application/views/viewFinishes.ejs
- application/views/viewMachines.ejs
- application/views/viewMaterials.ejs
This PR gives a user the ability to UPDATE and DELETE 3 objects (aka database tables).
1. `FINISH`
2. `MATERIAL`
3. `MACHINE`
Previously, a user could only CREATE and VIEW these objects.
Therefore, this PR completes the CRUD functionality for these 3 objects.
> Add `UPDATE`/`DELETE` functionality to Objects

- env
I was testing a first commit by adding a space in the readme file.
> first test commit put space in readme file

- application/models/windingSetup.js
- application/views/createWindingSetup.ejs
- application/views/viewWindingSetups.ejs
- package-lock.json
- package.json
- test/models/windingSetup.spec.js
Previously, the object `WINDING_SETUP` has an attribute called `watchOutFor` which was a String.
That attribute has now been updated in this PR to accept an array of strings for its value
> Modify `WINDING_SETUP` Schema Definition

- application/controllers/cuttingSetupController.js
- application/controllers/printingSetupController.js
- application/controllers/windingSetupController.js
- application/models/windingSetup.js
- application/views/updateCuttingSetup.ejs
- application/views/updatePrintingSetup.ejs
- application/views/updateWindingSetup.ejs
- test/models/windingSetup.spec.js
Before this PR, a user had the ability to perform all CRUD functionality (except for UPDATE) on the following objects:
1. `CUTTING_SETUP`
2. `WINDING_SETUP`
3. `PRINTING_SETUP`
After this PR, a user can also perform UPDATE operations on these objects, and therefore completes all CRUD operations for these objects 🎊
> Add UPDATE functionality for objects: `CUTTING_SETUP`, `WINDING_SETUP`, `PRINTING_SETUP`

- application/controllers/userController.js
- application/middleware/authorize.js
- application/middleware/upload.js
- application/models/user.js
- application/views/profile.ejs
- package-lock.json
- package.json
Added ability for a user to upload a profile picture via their `/profile` page
> Feature user profile picture

- application/controllers/userController.js
- application/models/user.js
- application/views/profile.ejs
- test/models/user.spec.js
Previously, a non-functional form was created and displayed on the users `/profile` page.
This form is where a user would update their: 
1) username
2) fullName
3) jobRole
4) birthday
5) phoneNumber
After this PR, the submission of that form will actually update that User in the database.
> Feature: Allow Ability to Update User Info on Profile Page

- application/controllers/userController.js
- application/public/js/main.js
- application/views/partials/navbarMain.ejs
- application/views/profile.ejs
This PR exposes a brand new endpoint `GET /users/profile-picture` which can be called to retrieve a user's profile picture.
This PR also updates some front-end HTML pages to utilize this endpoint in order to display the user's profile picture (duh)
> Feature: Inject User Profile Picture Dynamically into HTML

- application/controllers/recipeController.js
- application/views/allRecipes.ejs
On the "recipes" page, there previously was a placeholder for the author's profile picture to be displayed.
After this PR, that placeholder is now replaced by the author's profile picture (if one exists).
The image below shows where the profile pictures are displayed (the screenshot was taken prior to making any changes)
> Feature: Display Recipe Author's Profile Picture

- application/controllers/recipeController.js
- application/public/js/main.js
- application/views/allRecipes.ejs
Previously, a non-functioning search bar was added to the U.I as seen in the image below
This PR "hooks up" that search bar to actually function.
Anything typed in that search bar will be sent as a query to the database table named `recipe` and any matching results will be returned and displayed on the U.I.
> Feature: Implement Text Based Search

- application/public/js/main.js
The prior PR #47 added the ability for a user to perform text searches.
The results that were displayed had a minor bug where the results from every search were displayed to the user and were not cleared on the U.I.
This PR resolves that issue.
> Fix Issue Where Prior Search Results were Not Being Cleared

- application/controllers/finishController.js
- application/controllers/machineController.js
- application/controllers/materialController.js
- application/views/adminPanel.ejs
- application/views/profile.ejs
- application/views/viewMaterials.ejs
Previously, 3 tables were added to the `/admin` panel route that displayed nothing.
This PR populates those tables using AJAX
> Feature: Populate Admin Panel Tables with AJAX

- application/public/css/main.css
- application/public/js/main.js
- application/views/allRecipes.ejs
- application/views/profile.ejs
Fixed the profile image Gavin gave me. Created front-end ascending/descending arrows for filtering table columns. Also created an alert to give Gavin and ID when clicking on the column.
> Storms sixth sprint

- application/controllers/userController.js
- application/public/js/main.js
- application/views/partials/navbarMain.ejs
Before this PR, user details (such as username and job title) were hardcoded on the navbar.
After this PR, these values are set dynamically utilizing Ajax and Jquery.
> Details for navbar are pulled from a user's profile page
> Feature: Add User Details to Navbar

- application/public/css/main.css
- application/public/js/main.js
- application/views/partials/navbarMain.ejs
- application/views/viewCuttingSetups.ejs
fixes on the table view on a few pages and add the flexbox framework to css.
> minor fixes to tables

- application/controllers/recipeController.js
- application/public/js/main.js
- application/views/allRecipes.ejs
Previously, a table that contained many rows of data existed.
It was decided that it would be nice to sort these rows depending upon the values of a specific column - in ascending or descending order.
For example, if a user clicks on the "id" column, the rows displayed in the table should be automatically be sorted in `ascending` order (i.e. alphabetically)
If the user were to click the same "id" column a second time, the rows displayed in the table should automatically be sorted in `descending` order (i.e. reverse-alphabetically).
This allows a user much more flexibility to display data in the way they wish.
> Feature: Sort Rows on Column Click

- application/controllers/printingSetupController.js
- application/public/js/main.js
- application/views/allRecipes.ejs
- application/views/viewCuttingSetups.ejs
- application/views/viewPrintingSetups.ejs
- application/views/viewWindingSetups.ejs
Previously, an HTML table existed which displayed many `PrintingSetup` objects from the database.
It was decided that a cool feature would be to allow a user to sort the rows in that table after clicking on any of the column names.
This PR adds the feature that allows a user to sort the table according to any column of their choosing in either `ascending` or `descending` order.
> Sort PrintingSetup Columns on Click

- application/controllers/windingSetupController.js
- application/views/viewOneWindingSetup.ejs
- application/views/viewWindingSetups.ejs
Previously a page existed that displayed every `windingSetup` from the database via an HTML table.
After this PR, you can now click on any row of this table to view all the attributes on their very own page of whichever row was clicked.
> Add New Page to View any `WindingSetup` Individually

- application/controllers/cuttingSetupController.js
- application/controllers/printingSetupController.js
- application/views/viewCuttingSetups.ejs
- application/views/viewOneCuttingSetup.ejs
Previously a page existed that displayed every `cuttingSetup` object from the database via an HTML table.
After this PR, you can now click on any row of this table to view all the attributes on their very own page of whichever row was clicked.
> Add New Page to View any `CuttingSetup` Object Individually 

- application/controllers/vendorController.js
- application/index.js
- application/models/vendor.js
- application/public/js/admin-panel-tables.js
- application/views/adminPanel.ejs
- application/views/createFinish.ejs
- application/views/createMachine.ejs
- application/views/createVendor.ejs
- application/views/viewVendors.ejs
- test/models/vendor.spec.js
This PR adds a new database object called `vendor`. This PR adds front-end views that allow the user to CREATE these objects and View these objects.
This PR does not implement the UPDATE nor DELETE functionality for these objects, which will come in a later PR. 
> Vendors can be viewed/created via the `/admin` panel
> Add New Database Object Called `Vendor`

- application/controllers/finishController.js
- application/controllers/machineController.js
- application/controllers/materialController.js
- application/controllers/vendorController.js
- application/views/adminPanel.ejs
- application/views/updateVendor.ejs
Previously a database object named `Vendor` was created but only had CREATE/READ functionality.
This PR adds UPDATE/DELETE functionality to that object, thus completing all CRUD interactions for that object.
> Feature: Add UPDATE and DELETE Functionality to `Vendor` Objects

- application/controllers/materialOrdersController.js
- application/controllers/windingSetupController.js
- application/views/updateMaterial.ejs
- application/views/updateMaterialOrder.ejs
- application/views/updatePrintingSetup.ejs
- application/views/viewCuttingSetups.ejs
- application/views/viewMaterialOrders.ejs
- application/views/viewOneCuttingSetup.ejs
- application/views/viewOnePrintingSetup.ejs
- application/views/viewOneWindingSetup.ejs
- application/views/viewPrintingSetups.ejs
- application/views/viewWindingSetups.ejs
This PR adds the ability for a user to UPDATE/DELETE `materialOrder` objects.
A previous PR added the CREATE/READ functionality, so after this PR is merged, all CRUD functionality around this object is complete.
> Shows UPDATE/DELETE functionality a user can interact with
> Feature: Add UPDATE/DELETE Functionality to `materialOrder` Objects

- application/views/viewCuttingSetups.ejs
- application/views/viewMaterialOrders.ejs
- application/views/viewPrintingSetups.ejs
- application/views/viewWindingSetups.ejs
Every table row had an `href` such that a click anywhere on that row would route the user somewhere... However, other portions of that row need to have independent links, and thus, a conflicting routes were occuring
This PR fixes the issue.
> Bug: Fix Issue where Two User Click Interactions Overlapped on Table Rows

- application/controllers/materialOrdersController.js
- application/views/viewMaterialOrders.ejs
This PR adds the ability for a user to click on the name of a column on an HTML table, and all rows are sorted in either ASCENDING or DESCENDING order, based on the attribute the user clicked.
For example, if the user wishes to see all rows in ASCENDING order based on a `price` attribute, they can click on the column name `price` and all rows in the table will sort auto-magically.
> Feature: Sort Columns in ascending/descending Order on Column Name Click

- application/controllers/index.js
- application/controllers/userController.js
- application/services/userService.js
- test/services/userService.spec.js
Previously, a user who was logged in and had an active session was able to visit the login/register page, which led them to believe they needed to re-login.
This PR adds a check to the login and the register page, that will automatically redirect the user to their profile if a logged-in user visits the login page.
> Feature: Redirect User Away from Login/Register Page if Already Logged In

- application/controllers/cuttingSetupController.js
- application/controllers/materialOrdersController.js
- application/controllers/printingSetupController.js
- application/controllers/windingSetupController.js
- application/public/js/main.js
- application/views/viewCuttingSetups.ejs
- application/views/viewMaterialOrders.ejs
- application/views/viewPrintingSetups.ejs
- application/views/viewRecipes.ejs
- application/views/viewWindingSetups.ejs
Currently, many HTML tables are displayed throughout the site, each displaying different objects/attributes.
Each of these tables has a non-working searchbar, whose intended purpose is to allow a user to search through the table using keywords.
The goal is to get all of these searchbars working (duh) and this PR takes a step in the direction of doing this.
This PR does not finish this goal, however, it begins the intial setup work/refactor work and a future PR will finish the buildout.
> WIP Feature: Search Bar

- application/controllers/materialOrdersController.js
- application/models/materialOrder.js
- application/public/js/main.js
- test/models/materialOrder.spec.js
Previously a table existed that displayed all `materialOrder` objects from the database.
This table had a non-functioning searchbar.
After this PR, that search bar is now able to search/sort rows in that table based upon a few searchable attributes.
> The non-functioning searchbar that previously existed
> Un-styled search results (Styling will be done in a later PR)
> Add Search Functionality for `materialOrder` Objects

- application/models/product.js
- application/services/ticketService.js
- test/models/product.spec.js
Previously, a `PRODUCT` database object existed with many validation rules across its many attributes.
However, it was discovered that this object was missing a few attributes.
This PR adds those missing attributes and also adds validation rules around those attributes.
#NoSqlNoProblem
> Add Missing Attributes and Validation Rules to `PRODUCT` Database Object

- application/models/product.js
- application/models/ticket.js
- test/models/product.spec.js
- test/models/ticket.spec.js
A few attributes are computed dynamically based on other attribute values on both the TICKET and PRODUCT database objects.
Below are the computed attributes for these objects:
TICKET:
- totalLabelQty
- totalWindingRolls
PRODUCT:
- totalWindingRolls
- coreHeight
> Add Computed Attributes to TICKET and PRODUCT Objects

- application/controllers/materialController.js
- application/models/material.js
- application/public/js/admin-panel-tables.js
- application/views/adminPanel.ejs
- application/views/createMaterial.ejs
- application/views/updateMaterial.ejs
- application/views/viewMaterials.ejs
- test/models/material.spec.js
It was determined that MATERIAL database objects required a new field called `materialId`.
This PR makes the necessary changes to add that attribute across the server/client.
> Feature: Add `materialId` attribute to `MATERIAL` object

- application/views/viewTickets.ejs
In previous PR(s) 2 HTML pages were created which allowed for CREATING a ticket object and UPDATING a ticket object.
This PR add links/buttons that can be used by a user to view those pages:
> Add Links to UPDATE/CREATE a TICKET HTML Pages

- application/controllers/userController.js
- application/views/updateTicket.ejs
This PR resolves #89 by limiting the profile picture size from 3.5 MB to 800KB
> Limit Profile Picture Size

- README.md
Add link to Heroku website in README
> Update README with link to Heroku Hosted Website

- application/views/viewTickets.ejs
Previously clicking the "See All" button did nothing.
Now, clicking that button will result in a GET "/tickets" page which will simply cause a page refresh
> Make "See All" Button Work on `viewTickets.ejs`

- application/public/css/main.css
- application/public/css/workflow.css
- application/public/js/main.js
- application/views/adminPanel.ejs
- application/views/createMaterialOrder.ejs
- application/views/partials/navbarMain.ejs
- application/views/uploadTicket.ejs
- application/views/viewMaterialOrders.ejs
- application/views/viewRecipes.ejs
- application/views/viewTickets.ejs
Style changes to all the tables. All departments have options to view ticket or sub products. Also made design changes to the workflow pages.
> Storms branch oct 23

- application/controllers/productController.js
- application/services/productService.js
- application/views/viewOneProduct.ejs
- application/views/viewTickets.ejs
- test/services/productService.spec.js
This PR adds a page that displays all attributes on a `product` database object.
This PR adds the necessary controller/service/endpoint/views in order to wire it up
> Add `viewOneProduct.ejs` Page

- application/enums/priorityEnum.js
- application/models/ticket.js
- test/models/ticket.spec.js
After discussions, it was determined that the attribute `ticket.priority` needs to be one of the following values:
1. Rush Fee
2. ReRun
3. Hot
4. Standard
If not defined explicitly, this attribute must default to `Standard`.
This PR does all those things.
> Update Validation of `priority` attribute on `ticket` Object

- application/controllers/ticketController.js
- application/models/product.js
- application/services/ticketService.js
- test/models/product.spec.js
The main purpose of this PR was to fix the function `removeEmptyObjectAttributes` which had an issue where attempted to loop over a value which was previously expected to always be an array.
However, sometimes the variable it was trying to loop over was a string, resulting in an error.
The fix was to check if the value is an array first, and if not, make it an array.
This PR also makes several validation updates to the attribute `productNumber` on the object `product`. After some discussions, it was determined that the existing validation rules for that attribute were no longer valid.
That work is unrelated, but I added it to this PR anyway.
> Ticket Upload Fixes and Schema Changes

- application/public/css/buttons.css
- application/public/css/main.css
- application/public/css/workflow.css
- application/views/adminPanel.ejs
- application/views/uploadTicket.ejs
- application/views/viewMaterialInventory.ejs
- application/views/viewOneProduct.ejs
initial ticket view design setup in place
> initial ticket view design setup

- application/views/viewTickets.ejs
Currently, a ticket object can be in 1 of 8 departments.
This PR counts the number of tickets in each of those departments and displays the count on the UI.
> Display the Number of Tickets in every Department on the UI

- application/public/css/main.css
- application/public/css/workflow.css
- application/public/js/main.js
- application/views/partials/sidebarMain.ejs
- application/views/viewTickets.ejs
Side navbar v2 built. Cleaned up a few things on viewTickets.ejs
> Storms branch nov 2

- application/public/css/main.css
- application/public/css/workflow.css
- application/public/js/main.js
- application/views/partials/navbarMain.ejs
- application/views/partials/sidebarMain.ejs
- application/views/viewTickets.ejs
updated navbar links. general ui edits
> updated navbar links. general ui edits

- application/public/css/main.css
- application/public/css/workflow.css
- application/public/js/main.js
- application/views/partials/navbarMain.ejs
- application/views/partials/sidebarMain.ejs
- application/views/viewTickets.ejs
new navigation design and layout. Includes the new settings dropdown design and layout.
> new navigation design and layout. Including the settings dropdown design

- application/controllers/ticketController.js
- application/enums/departmentsEnum.js
- application/index.js
- application/services/dateTimeService.js
- application/services/ejsService.js
- application/services/ticketService.js
- application/services/userService.js
- application/services/workflowStepService.js
- application/views/viewTickets.ejs
- test/enums/departmentsEnum.spec.js
- test/services/dateTimeService.spec.js
- test/services/ejsService.spec.js
- test/services/workflowStepService.spec.js
This PR deals with displaying the duration a ticket has been in various states on the.
A ticket has a `department` and a `departmentStatus` attribute. The system currently tracks when and how long a ticket has had been in the various department/departmentsStatuses for audit purposes.
This PR presents this data to the user visually.
It does a lot of fun dateTime computations
> These fields now dynamically populate on the UI
> Display how Much Time Tickets have Spent at Each Department/DepartmentStatus on the User Interface (UI)

- application/public/css/main.css
- application/views/partials/navbarMain.ejs
minor placeholder list options added to the settings navbar
> minor placeholder list options added to the settings navbar

- application/public/css/main.css
- application/public/js/main.js
- application/views/partials/navbarMain.ejs
- application/views/viewTickets.ejs
Created a function for Gavin so when a user selects a department they would like to send a ticket to, the function grabs the data-attribute and console logs it.
> Storms branch nov 9

- application/views/viewTickets.ejs
This PR adds several HTML sections to `viewTickets.ejs` which were found to be missing or in need of an update.
These sections are:
1. orderPrep.inProgress
2. printing.schedulePressThree
3. billing.readyForBilling
4. billing.inProgress
There also was a UI bug which resulted in the page crashing whenever a ticket was added to the section orderPrep.needsAttention. This was caused by one too many closing div tags (</div>). The issue was resolved when I deleted the extra closing div tag.
I went through and moved a its department/departmentStatus through every section and saw the ticket move on the UI to the appropriate section as I would expect
> Fix `Billing` Section on `viewTickets.ejs`

- application/public/js/main.js
- application/views/viewTickets.ejs
created a function when a user clicks to move ticket to new department or status it console logs the ticket id, department, and status.
> Storms laptop branch nov 11

- application/controllers/materialInventory.js
Removing log statements that are no longer needed
> Remove Logging Code that Snuck in During Development

- application/views/viewTickets.ejs
Previously, ejs code on the front-end HTML pages was preventing certain HTML sections from being displayed.
It was decided that we instead want to display these HTML sections no matter what for reasons.
This PR makes that change.
> Always Render all Departments/DepartmentStatus HTML Sections in `viewTickets.ejs`

- application/views/partials/ticket-dropdown-options.ejs
- application/views/viewTickets.ejs
A major refactor was done and many HTML ids/classes that the front-end javascript relies on accidentally were removed.
This PR adds those back
> Fix Broken Move Functionality

- application/public/css/main.css
- application/views/partials/navbarMain.ejs
- application/views/partials/sidebarMain.ejs
- application/views/partials/ticket-dropdown-options.ejs
- application/views/partials/workflow-navigation.ejs
- application/views/partials/workflow-sorting-filtering.ejs
- application/views/viewTickets.ejs
This guy thinks he can CSS (lol)
> playing around with department header colors

- application/public/js/main.js
- application/views/partials/department-status-clones.ejs
- application/views/viewTickets.ejs
Currently on `viewTickets.ejs` there are severals tables. Each table stores many rows. Each row represents a `Ticket` object.
We want the ability to move a ticket row from one table to another.
However, not all the tables have the same columns so therefore, I needed to write some javascript that detects which columns a given table has, and inject the proper column values when the ticket is moved.
This PR makes that magic happen, I find how I implemented it satisfyingly clever 😃
> Feature: Move Ticket (WIP)

- test/models/ticket.spec.js
A previous PR added [mongoose pre-hooks](https://github.com/gavinvaske/the_recipe_book/pull/141/files#r1014894508).
This code was left untested and an issue was created to come back and fix that.
This PR fixes the issue by testing that code.
This PR closes #144 
Functionally this code works great, however the test setup and test code is long and will probably make the next guy (me) who needs to change it sad. :shipit:
> Add Missing Test Cases For Mongoose Pre Hooks

- application/public/js/main.js
Why did I make this PR?
I needed to refactor jQuery to work with injecting elements without a refresh
> Storms laptop branch nov 26

- application/controllers/ticketController.js
- application/public/js/main.js
- application/services/ticketService.js
- application/services/workflowStepService.js
- test/services/ticketService.spec.js
Prior to this PR, when a ticket is moved from one departmentStatus table to another departmentStatus table, several HTML attributes were hardcode and not dynamically populated correctly.
This PR dynamically populates the links and duration information utilizing JQUERY/AJAX on the moved ticket.
> Feature: Dynamically Populate Links and Duration on Moved Tickets

- package-lock.json
- package.json
This PR follows #197 and makes another update to a dependency I missed.
I also think the package-lock was out of sync but this PR will fix that issue.
> update dependency `mongodb-memory-server` and fix package-lock

- .circleci/config.yml
This PR was created to fix the CircleCi ci/cd pipeline which is currently failing.
> Tests are now running and passing
https://docs.cypress.io/guides/continuous-integration/circleci#What-you-ll-learn
> Fix ci cd pipeline

- .circleci/config.yml
- cypress.config.js
- cypress/e2e/spec.cy.js
- cypress/support/e2e.js
- package.json
Previously, the CI/CD pipeline ran all the tests, but I forgot to trigger the linter as well.
This PR updates the commands executed during the ci/cd pipeline to also run the linter.
> refactor: update ci/cd pipeline to also run linter

- application/views/viewTickets.ejs
- test/models/ticketGroup.spec.js
Noticed one line of HTML/CSS that was not needed, this PR removes it.
> Minor Refactor to Remove Unneeded CSS

- application/controllers/ticketController.js
- application/public/js/main.js
- application/views/partials/start-job-modal.ejs
- application/views/partials/ticketTableColumns/user-column.ejs
This PR does two things.
1. When a user clicks "start ticket" on one ticket row within viewTickets.ejs, they (the logged in user) is assigned to that ticket object in the database
2. When the ticket the user has been assigned to is rendered on viewTickets.ejs, the profile picture of the user who clicked the start button is displayed, as well as their name and other information.
> User's picture is displayed on page (note, the CSS styles have not been applied to format the size, that is coming in a different PR)
> Feature: Display Profile Pictures in viewTickets.ejs and Make "Start Ticket" button work

- .eslintrc.js
- application/models/destination.js
- application/models/machine.js
- application/public/js/main.js
- application/views/partials/start-job-modal.ejs
- test/models/machine.spec.js
When a user starts a ticket, they have the option of assigning that ticket to a specific machine.
This PR makes that assignment functionality work.
> Populate Machines Dropdown on `Start Ticket` Modal

- application/public/js/main.js
- application/views/viewOneInProgressTicket.ejs
Previously, placeholder UI work was done to show information on the `viewOneInProgressTicket` page.
This PR now makes that information display dynamically
> Populate Product Info Dynamically on `ViewOneInProgressTicket.ejs`

- application/controllers/dieLineCardController.js
- application/controllers/proofCardController.js
- application/controllers/spotPlateCardController.js
- application/controllers/ticketCardController.js
- application/index.js
- application/views/createDieLine.ejs
- application/views/createProof.ejs
- application/views/createSpotPlate.ejs
- application/views/partials/ticket-table.ejs
- application/views/partials/workflow-sorting-filtering.ejs
- application/views/uploadTicket.ejs
- application/views/viewTickets.ejs
- test/models/ticket.spec.js
This PR does a couple things (ideally this would be 2 PRs, but I'm a one-man team so 👀 )
* Adds 3 new front-end `.ejs` views and creates 3 new controllers that handle rendering those views
* Adds a new configuration parameter called `cssClassToUseForTableColoring` that can be passed into an ejs file during render to apply css styles
> Add new Routes for Cards

- application/controllers/dieLineController.js
- application/controllers/productController.js
- application/controllers/spotPlateController.js
- application/public/js/main.js
- application/schemas/product.js
- application/schemas/s3File.js
- application/services/fileService.js
- application/services/s3Service.js
- application/views/viewOneInProgressTicket.ejs
- package-lock.json
- package.json
- test/schemas/product.spec.js
- test/schemas/s3File.spec.js
- test/services/fileService.spec.js
- test/services/s3Service.spec.js
This PR refactors two main files: `s3FilesService.js` and `fileService.js` to handle CRUDing files on the server and on an S3 bucket.
This PR also adds a feature to the page `/tickets/in-progress/:ticketId` such that a user can see a preview of a PDF stored in an S3 bucket on the UI.
> This screenshot shows the PDF preview that is rendered. This PDF is stored in an S3 bucket and the S3 URL is injected dynamically
> Show Proofs in a PDF preview Window on `/tickets/in-progress/:ticketId` Page

- application/public/js/main.js
- application/schemas/product.js
- application/views/viewOneInProgressTicket.ejs
- test/schemas/product.spec.js
This PR does a couple things. Currently on the page `/in-progress/:ticketId` a PDF preview is rendered on the page. This PR ensures that a default pdf is shown if one does not exist (ticket.products[n].proofUrl === '')
If one does exist, this PR ensures that the AJAX populates the correct URL in the PDF preview.
This PR also adds an attribute `product.finishes` which is a calculated attribute based on a couple criteria and renders it on the UI
> Miscellaneous Bug Fixes

- application/controllers/materialController.js
- application/models/material.js
- application/views/adminPanel.ejs
- application/views/createMaterial.ejs
- application/views/updateMaterial.ejs
- application/views/viewMaterialInventory.ejs
- application/views/viewMaterials.ejs
- test/models/material.spec.js
A new attribute `material.vendorId` was added in this PR.
This change required updates to the database schema, as well as to the front-end pages used to SET/UPDATE this value.
> New HTML form field added to the create form
> New field added to the Update form
> Add `material.vendorId` Attribute and Update Create/Update HTML pages

- application/controllers/cuttingSetupController.js
- application/controllers/finishController.js
- application/controllers/machineController.js
- application/controllers/materialCategoryController.js
- application/controllers/materialController.js
- application/controllers/materialOrdersController.js
- application/controllers/printingSetupController.js
- application/controllers/recipeController.js
- application/controllers/vendorController.js
- application/controllers/windingSetupController.js
- application/index.js
- application/models/materialCategory.js
- application/views/createMaterialCategory.ejs
- application/views/updateMaterialCategory.ejs
- application/views/viewMaterialCategories.ejs
- test/models/materialCategory.spec.js
This PR adds a new mongoDb database table called `materialCategory`.
This PR also implements all CRUD endpoints required to interact with this database table. As well as adds all the necessary front-end UI views.
> New Database Table `materialCategory` and CRUD Functionality

- .circleci/config.yml
- application/controllers/filePlanController.js
- application/index.js
- application/services/distributionGeneratorService.js
- application/services/filePlanService.js
- application/views/createFilePlan.ejs
- package-lock.json
- package.json
- test/services/distributionGeneratorService.spec.js
- test/services/filePlanService.spec.js
This PR does two things:
1. Creates an algorithm
2. Creates a UI for a user to utilize this algorithm
By far, this is the most useful algorithm I've built for this project.
Some definitions: A product is a label. A product has a labelQuantity.
A job has many products, and these products need to be split into batches efficiently. Too many batches (aka 1 product per batch) results in a large amount of inefficiencies.
The goal is to minimize the number of batches within physical bounds (i.e. `labelsAcross`, `labelsAround`, `labelQuantity`, etc)
This PR adds an algorithm that computes the minimum number of batches required to print a set of products.
This previously was a very manual amount of work that required a lot of math-ing and was very prone to error.
It took weeks to come up with and …
> Feature: File Plan Algorithm

- .circleci/config.yml
- application/services/filePlanService.js
- test/services/filePlanService.spec.js
The current algorithm for generating file plans has many flaws, but semi works a lot of time.
This PR updates the algorithm to fix some obviously wrong problems with it.
However, this PR still hasn't perfected the algorithm, it has only created an algorithm that finds a local minimum.
Future PR(s) will fix the algorithm.
Also, note that one test case is commented out. That test case is great.. But, the algorithm currently doesn't make it pass.
> Improve File Plan Algorithm

- README.md
This PR adds a section to the readme that describes how to store various data in database tables this application uses
> Add Database Standards to `README.md`

- application/views/createPackagingEstimate.ejs
A prior PR set a default value for an HTML input field to the wrong value. This PR fixes that.
> minor default value change

- application/controllers/materialController.js
- application/controllers/quoteController.js
- application/index.js
- application/views/createQuote.ejs
- test/services/packagingService.spec.js
Adding a page a user will utilize to create a `Quote` object.
That object is being added in a different PR. This PR just adds a UI page so we can start putting the UI together while the backend Quote database stuff is worked on in parallel.
> Ddd QuoteController and add `createQuote.ejs` Page

- test/services/quoteService.spec.js
- test/testDataGenerator.js
This PR fixes a flaky test by adjusting the range of randomly generated test data to make it more reasonable and avoid the sneaky failures
> Fix Flaky Test

- package-lock.json
- package.json
This PR moves a few devDependencies in package.json into normal dependencies.
Previously, heroku was failing to start the production server because heroku doesn't install dev dependencies and it turns out, a few were required to start the server
> Fix Production Dependency Issue

- application/models/quote.js
- application/services/quoteService.js
- test/models/quote.spec.js
- test/services/quoteService.spec.js
The database model `Quote` was missing some attributes.
This PR adds those attributes, as well as the formulas for those attributes.
> Add Quote Attributes

- application/react/Quote/CostSummary/CostSummary.js
- application/react/Quote/InputSection/InputFields/LabelsPerRoll/LabelsPerRoll.js
- application/react/Quote/InputSection/InputSection.js
- application/react/Quote/OutputSection/OutputSection.js
In this PR I cleanup the UI page on `/quote/form` (aka the create quote page)
This UI page is still in development but this PR cleans up a lot of the wip.
Future PRs to come
> Cleaning up Create Quote UI Page

- application/react/Quote/CostSummary/CostSummary.js
- application/react/Quote/InputSection/InputFields/TextField/TextField.js
- application/react/Quote/OutputSection/OutputSection.js
- application/react/Quote/TableRow/TableRow.js
- application/react/utils/formatters.js
- test/models/customer.spec.js
Previously, the Create Quote page was rendering calculations with unformatted values. (i.e some decimals had way to many decimals showing, currency was displaying in pennies, time was displaying in seconds)
This PR adds react utility methods that parse the "barely readable" values and make "human readable"
> Refactor Create Quote Page

- package-lock.json
- package.json
After running `npm audit` - there were a list of vulnerabilities in dependencies that needed addressing.
This PR updates dependencies to fix all those issues
> Fix `npm audit` Vulnerabilities

- package-lock.json
package-lock got out of whack.... so I deleted it and regenerated it
> Regenerating `package-lock`

- application/models/linerType.js
- application/models/material.js
- application/react/_global/FormModal/FormModal.js
- application/react/_types/databaseModels/material.tsx
- package.json
- test/models/linerType.spec.js
- test/models/material.spec.js
- test/schemas/product.spec.js
- test/testDataGenerator.js
This PR does two things:
1. Adds new database table: `LinerType`
2. Adds attributes to database table: `Material`
> Add db model `LinerType`

- application/controllers/linerTypeController.js
- application/controllers/materialController.js
- application/index.js
- application/react/App/App.tsx
- application/react/CreditTerms/CreditTermsForm/CreditTermsForm.tsx
- application/react/DeliveryMethod/DeliveryMethodForm/DeliveryMethodForm.tsx
- application/react/LinerType/LinerTypeForm/LinerTypeForm.tsx
- application/react/LinerType/LinerTypeTable/LinerTypeTable.tsx
- application/react/_global/FlashMessage/FlashMessages.scss
- application/react/_global/FlashMessage/FlashMessages.tsx
- application/react/_global/FlashMessagePanel/FlashMessagePanel.scss
- application/react/_global/FlashMessagePanel/FlashMessagePanel.tsx
- application/react/_types/FlashMessage.ts
- application/react/_types/databaseModels/linerType.tsx
- application/react/_types/forms/linerType.tsx
- application/react/_types/tsHelpers.ts
- application/react/index.js
- application/react/stores/flashMessagesStore.ts
- application/react/stores/quoteStore.ts
- package-lock.json
- package.json
- test/models/material.spec.js
This PR does a couple things.
1. Sets up the database to handle `LinerType` objects and adds new react Views related to this object
2. Implements a reusable method for displaying success and error messages to the user
> Add Ability to Create `LinerType` AND implement Flash Messages in React

- application/react/Inventory/Materials/Material/Material.scss
- application/react/_global/FlashMessagePanel/FlashMessagePanel.scss
- application/react/_global/FlashMessagePanel/FlashMessagePanel.tsx
Flash alert container html/scss styling. 
Flash alert success html/scss styling.
Flash alert error html/scss styling.
> styled the flash alerts from gavin

- application/react/CreditTerms/CreditTermsTable/CreditTermsTable.tsx
- application/react/DeliveryMethod/DeliveryMethodTable/DeliveryMethodTable.tsx
- application/react/_types/Filters.ts
- application/react/stores/inventorySummaryStore.ts
I noticed a few random things that needed to be refactored, this PR makes those changes
> Sporatic Refactoring

- application/react/App/App.tsx
- application/react/Footer/Footer.tsx
- application/react/Navbars/HorizontalNavbar/HorizontalNavbar.tsx
- application/react/_layouts/TopNavbarLayout.tsx
This PR introduces the react concept known as "Layouts".
This PR adds a Layout which includes a placeholder navbar and footer
The navbar and footer will be built and pushed in a different PR
> Setup `Layout` component and Create Placeholder Navbar and Footer

- application/react/Address/AddressForm/AddressForm.tsx
- application/react/CreditTerm/CreditTermForm/CreditTermForm.tsx
- application/react/Customer/Contact/ContactForm/ContactForm.tsx
- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/DeliveryMethod/DeliveryMethodForm/DeliveryMethodForm.tsx
- application/react/ShippingLocation/ShippingLocationForm/ShippingLocationForm.tsx
- application/react/_global/FormInputs/Select/Select.tsx
Previously, I created custom Select and Input components in react
I noticed a few locations that were still using regular ole' html <input> and <select> elements
This PR removes those, and instead uses my custom components.
Also, this PR adds the ability for Select to be a multi-select
> Use Custom `<Select />` and `<Input />` Components

- application/controllers/adhesiveCategoryController.js
- application/controllers/creditTermsController.js
- application/controllers/customerController.js
- application/react/AdhesiveCategory/AdhesiveCategoryTable/AdhesiveCategoryRowActions/AdhesiveCategoryRowActions.tsx
- application/react/AdhesiveCategory/AdhesiveCategoryTable/AdhesiveCategoryTable.tsx
- application/react/App/App.tsx
- application/react/CreditTerm/CreditTermTable/CreditTermTable.tsx
- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/Customer/CustomerTable/CustomerRowActions/CustomerRowActions.tsx
- application/react/Customer/CustomerTable/CustomerTable.tsx
- application/react/Material/MaterialForm/MaterialForm.tsx
- application/react/_global/SearchBar/SearchBar.tsx
- application/react/_queries/adhesiveCategory.ts
- application/react/_queries/customer.ts
- cypress/e2e/adhesive-category.cy.ts
- cypress/e2e/credit-term.cy.ts
- cypress/e2e/customer.cy.ts
- cypress/e2e/delivery-method.cy.ts
- cypress/e2e/inventory.cy.ts
- cypress/e2e/liner-type.cy.ts
- cypress/e2e/material.cy.ts
- test/models/material.spec.js
This PR adds two tables which display `Customers` and `AdhesiveCategories`
From those tables, a user can also select to `edit` or `delete` the corresponding option.
This PR also does some work with the e2e tests (written in cypress)
> Add Tables for `Customer` and `Adhesive-Category`

- .vscode/settings.json
- application/controllers/materialOrdersController.js
- application/controllers/userController.js
- application/enums/mongooseSortMethods.js
- application/models/user.js
- application/react/App/App.tsx
- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- application/react/MaterialOrder/MaterialOrderTable/MaterialOrderRowActions/MaterialOrderRowActions.tsx
- application/react/MaterialOrder/MaterialOrderTable/MaterialOrderTable.tsx
- application/react/_global/FormInputs/Input/Input.tsx
- application/react/_global/FormInputs/Select/Select.tsx
- application/react/_helperFunctions/dateTime.ts
- application/react/_queries/materialOrder.ts
- application/react/_queries/users.ts
- application/react/_queries/vendors.ts
- application/react/_types/databaseModels/materialOrder.ts
- application/react/_types/databaseModels/user.ts
- cypress/e2e/material-order.cy.ts
- test/models/linerType.spec.js
We currently have a database table called `material_orders`
However, we didn't have anything on the UI setup to render these items or to create these items.
This PR adds a Table and a Form which enables all CRUD functionality on these objects.
> Add `Form` and `Table` components for `MaterialOrder` database object

- application/api/tsconfig.json
- package-lock.json
- package.json
Fixing a couple minor issues I came across after a recent huge refactor
> Minor Misc. Refactors

- application/api/services/emailService.ts
- application/react/_auth/Login/Login.tsx
- application/views/partials/navbarMain.ejs
Twilio password reset access changes. Added storm@thelabelfactory.com as the sender. Changed the register button id to not be duplicated with the forgot password button.
> Storm aug 14

- application/api/services/databaseService.ts
- application/react/Customer/CustomerTable/CustomerRowActions/CustomerRowActions.tsx
This PR does a couple small things. Most notably, adds a link from the "customer" table to "View one Customer" page
> Misc. Changes

- test/models/customer.spec.js
- test/models/material.spec.js
- test/models/user.spec.js
There's been a long-term issue (#370)
This PR resolves #370
> Fix Flaky Tests

- application/react/App/App.tsx
- application/react/Navbars/Navbar/Navbar.tsx
- application/react/_context/dropdownProvider.tsx
- application/react/_global/Dropdown/Dropdown.tsx
Previously, dropdowns never closed once they were opened. Ideally when a dropdown is open and a user clicks elsewhere on the screen, or opens another dropdown, the prior one is closed automatically.
This PR does that using "fancy" react context
> Close Dropdowns

- package-lock.json
- package.json
When deploying this application, a dev dependency is required, but since dev dependencies aren't installed, the build is failing - this PR fixes that
> Move dev-dependency to Fix Failing Prod Build

- package-lock.json
- package.json
Parcel is failing to build in production, mentioning that process is not available. This PR moves that dependency out of dev-dep list
> Move Dev Dependency

- .vscode/extensions.json
- application/api/models/material.ts
- application/api/models/materialOrder.ts
- application/api/services/currencyService.ts
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- application/react/_queries/materialOrder.ts
- test/models/materialOrder.spec.js
- test/services/currencyService.spec.js
Setup new attributes for `MaterialOrder`:
1. freightCharge: Currency, non-negative
2. fuelCharge: Currency, non-negative
Update UI pages (create/edit) related to MaterialOrder
> Add `MaterialOrder` Attributes

- application/api/models/material.ts
- application/react/Inventory/Inventory.tsx
- application/react/Inventory/Materials/Material/Material.scss
- application/react/Inventory/Materials/Material/Material.tsx
- application/react/Material/MaterialForm/MaterialForm.tsx
- test/models/material.spec.js
- test/testDataGenerator.ts
This PR adds a new db field `Material.minFootageAlertThreshold`
The idea behind this, if an material's inventory falls below a certain threshold, a UI change occurs (a color change) to easily spot this.
> Setup Low Material Inventory Alert

- cypress/e2e/material-length-adjustement.cy.ts
I previously merged a PR that added a new ui route and table. This PR adds a missing cypress test around that work
> Add Cypress Test

- application/react/AdhesiveCategory/AdhesiveCategoryTable/AdhesiveCategoryTable.tsx
- application/react/CreditTerm/CreditTermTable/CreditTermTable.tsx
- application/react/Customer/CustomerTable/CustomerTable.tsx
- application/react/DeliveryMethod/DeliveryMethodTable/DeliveryMethodTable.tsx
- application/react/Die/DieTable/DieTable.tsx
- application/react/LinerType/LinerTypeTable/LinerTypeTable.tsx
- application/react/Material/MaterialTable/MaterialTable.tsx
- application/react/MaterialOrder/MaterialOrderTable/MaterialOrderTable.tsx
- application/react/Product/ProductTable/ProductTable.tsx
- application/react/Quote/QuoteTable/QuoteTable.tsx
In this PR, I went through all the tables we had and applied general formatting to Date/DateTime columns. I also added a few columns I know we'll need, more column updates to come later
> Misc. Table Formatting

- application/_types/shared/models.ts
- application/_types/shared/schemas.ts
- application/api/controllers/vendorController.ts
- application/api/models/customer.ts
- application/api/models/vendor.ts
- application/api/schemas/address.ts
- application/api/schemas/contact.ts
- application/react/Customer/ViewCustomer/ViewCustomer.tsx
- application/react/Die/DieTable/DieTable.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable.tsx
- application/react/Vendor/VendorTable/VendorTable.tsx
This PR enables text searching / pagination on the `vendor` table
This PR also migrates vendor types to a shared directory for use by backend and frontend
> Setup Searching/Pagination on `Vendor` Table

- application/_types/shared/models.ts
- application/_types/shared/schemas.ts
- application/api/controllers/customerController.ts
- application/api/controllers/dieController.ts
- application/api/controllers/materialLengthAdjustmentController.ts
- application/api/controllers/materialOrdersController.ts
- application/api/models/creditTerm.ts
- application/api/models/customer.ts
- application/api/schemas/contact.ts
- application/react/Customer/CustomerTable/CustomerRowActions/CustomerRowActions.tsx
- application/react/Customer/CustomerTable/CustomerTable.tsx
- application/react/Customer/ViewCustomer/ViewCustomer.tsx
- application/react/Die/DieTable/DieTable.tsx
- application/react/_queries/customer.ts
This PR sets up a /customers/search endpoint and updates the CustomerTable component to allow users to search for customers using a searchfield and paginate the results
> Enable Search / Pagination on `Customer` table

- application/api/controllers/materialController.ts
- application/react/Material/MaterialForm/MaterialForm.tsx
- application/react/Material/MaterialTable/MaterialTable.tsx
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- application/react/MaterialOrder/MaterialOrderTable/MaterialOrderTable.tsx
- application/react/Product/ProductForm/ProductForm.tsx
- application/react/_queries/material.ts
- application/react/_queries/materialOrder.ts
This PR allows a user to search for Materials using a searchbar on the Material Table.
This PR also adds pagination to the material table
> Enable Searching/Pagination on `Material` Table

- application/api/controllers/creditTermsController.ts
- application/api/controllers/materialLengthAdjustmentController.ts
- application/api/controllers/materialOrdersController.ts
- application/api/controllers/vendorController.ts
- application/api/models/creditTerm.ts
- application/api/models/materialOrder.ts
- application/react/CreditTerm/CreditTermTable/CreditTermTable.tsx
- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/Material/MaterialTable/MaterialTable.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- application/react/MaterialOrder/MaterialOrderTable/MaterialOrderTable.tsx
- application/react/_queries/vendors.ts
I recently merged a ton of PRs that made drastic typescript / table pagination related changes.
This PR cleansup some messes that were leftover
Update: I got carried away and also added Server Side Pagination to `creditTerm` Table
> Misc. Fixes & `CreditTerm` Table Searching/Pagination

- application/_types/shared/models.ts
- application/api/controllers/adhesiveCategoryController.ts
- application/api/controllers/linerTypeController.ts
- application/api/controllers/materialCategoryController.ts
- application/api/models/adhesiveCategory.ts
- application/api/models/linerType.ts
- application/api/models/materialCategory.ts
- application/react/AdhesiveCategory/AdhesiveCategoryForm/AdhesiveCategoryForm.tsx
- application/react/AdhesiveCategory/AdhesiveCategoryTable/AdhesiveCategoryTable.tsx
- application/react/App/App.tsx
- application/react/CreditTerm/CreditTermForm/CreditTermForm.tsx
- application/react/DeliveryMethod/DeliveryMethodForm/DeliveryMethodForm.tsx
- application/react/DeliveryMethod/DeliveryMethodTable/DeliveryMethodRowActions/DeliveryMethodRowActions.tsx
- application/react/LinerType/LinerTypeForm/LinerTypeForm.tsx
- application/react/LinerType/LinerTypeTable/LinerTypeRowActions/LinerTypeRowActions.tsx
- application/react/LinerType/LinerTypeTable/LinerTypeTable.tsx
- application/react/Material/MaterialForm/MaterialForm.tsx
- application/react/Material/MaterialTable/MaterialRowActions/MaterialRowActions.tsx
- application/react/MaterialCategory/MaterialCategoryForm/MaterialCategoryForm.tsx
- application/react/MaterialCategory/MaterialCategoryTable/MaterialCategoryRowActions/MaterialCategoryRowActions.tsx
- application/react/MaterialCategory/MaterialCategoryTable/MaterialCategoryTable.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentRowActions/MaterialLengthAdjustmentRowActions.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable.tsx
- application/react/Product/ProductForm/ProductForm.tsx
- application/react/Quote/QuoteTable/QuoteRowActions/QuoteRowActions.tsx
- application/react/Vendor/VendorTable/VendorTable.tsx
- application/react/_queries/adhesiveCategory.ts
- application/react/_queries/linerType.ts
- application/react/_queries/materialCategory.ts
- cypress/e2e/material-category.cy.ts
This PR adds a bunch of new UI pages I noticed were missing
And also a ton of style changes
Wayyy too much was done in this PR - butttt... It's done now, soooo...
> Add Missing UI Pages`linerType`/`AdhesiveCategory`/`MaterialCategory` & Misc. Style Changes

- application/_types/shared/models.ts
- application/api/models/material.ts
- application/react/Inventory/Materials/Material/Material.tsx
- application/react/Inventory/Materials/Materials.tsx
- application/react/Material/MaterialForm/MaterialForm.tsx
- test/models/material.spec.js
- test/testDataGenerator.ts
This PR adds UI styling to indicate if a material is low in inventory (error), or above the threshold but within a buffer (warning)
> Material Low Inventory UI Alerts

- application/_types/shared/models.ts
- application/api/models/die.ts
- application/react/Die/DieForm/DieForm.tsx
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- cypress/e2e/forgot-password.cy.ts
- test/models/die.spec.js
- test/testDataGenerator.ts
This PR adds a new attribute to the db: die.isLamination and updates the dieForm to allow users to set its' value
> add attribute: `die.isLamination`

- README.md
- application/react/_auth/Login/Login.scss
- application/react/_auth/Login/Login.tsx
- application/react/_global/FormInputs/Input/Input.scss
- application/react/_global/FormInputs/Input/Input.tsx
- package-lock.json
- package.json
The original ask was that the password input field needed an icon that enables a user to view or hide their typed password.
Since the password input field is a global shared component, this word either required creating a new one-off custom component, or enabling icons on the Input component. I chose the later, because icons are going to be needed on other input fields later on.
> Enable Icons on Input Component

- application/api/controllers/userController.ts
- application/react/AdminPanel/AdminPanel.tsx
- application/react/App/App.tsx
- application/react/MaterialOrder/MaterialOrderTable/MaterialOrderRowActions/MaterialOrderRowActions.tsx
- application/react/User/UserAuthRolesForm/UserAuthRolesForm.tsx
- application/react/User/UserTable/UserRowActions/UserRowActions.tsx
- application/react/User/UserTable/UserTable.tsx
- application/react/_global/SearchBar/SearchBar.tsx
- application/react/_global/Table/PageSelect/PageSelect.tsx
- application/react/_queries/users.ts
We don't have an easy method of checking which users are on the platform and performing general user management tasks like assigning permissions.
This PR adds a table that renders all users on the platform.
> Add `User` Table

- .eslintrc.cjs
- application/_enums/auth.ts
- application/api/controllers/authController.ts
- application/api/controllers/userController.ts
- application/api/routes.ts
- application/react/Inventory/Materials/Material/MaterialCard.scss
- application/react/Material/MaterialForm/MaterialForm.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- application/react/Navbars/Navbar/Navbar.tsx
- application/react/UploadProfilePicture/UploadProfilePicture.tsx
- application/react/User/Profile/Profile.tsx
- application/react/_global/FlashMessagePanel/FlashMessagePanel.scss
- application/react/_global/FlashMessagePanel/FlashMessagePanel.tsx
- application/react/_global/FormInputs/CustomSelect/CustomSelect.scss
- application/react/_hooks/useLoggedInUser.ts
- application/react/_queries/auth.ts
- application/react/_queries/users.ts
- tsconfig.base.json
This PR is a misc. combination of a few things, but mostly the expansion of useQuery for UX / Performance enhancments.
I also implements loading indicators more appropriately, such that an edit form doesn't render until the form values are pre populated, fixing a "flashing" UX issue.
This PR also adds a custom react hook `useLoggedInUser` for fetching details about the logged in user, such as name, profile picture, ect.
> Expand usage of `useQuery` for UX / Performance

- application/_types/shared/models.ts
- application/_types/ui/forms.ts
- application/react/User/Profile/Profile.tsx
- application/react/_global/FormInputs/CustomSelect/CustomSelect.scss
- application/react/_global/FormInputs/CustomSelect/CustomSelect.tsx
Previously we had dropdowns the showed a list of available options. Sometimes we have hundreds of options. This PR adds the ability to text search / filter the list of options.
> Make Dropdowns Searchable

- application/_enums/auth.ts
- application/_types/shared/models.ts
- application/api/controllers/userController.ts
- application/api/enums/authRolesEnum.ts
- application/api/middleware/authorize.ts
- application/api/models/vendor.ts
- application/react/AdhesiveCategory/AdhesiveCategoryTable/AdhesiveCategoryTable.tsx
- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/Die/DieForm/DieForm.tsx
- application/react/Material/MaterialForm/MaterialForm.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- application/react/Navbars/Navbar/Navbar.tsx
- application/react/User/UserTable/UserRowActions/UserRowActions.tsx
- application/react/User/UserTable/UserTable.tsx
- application/react/_auth/Login/Login.scss
- application/react/_auth/Login/Login.tsx
- application/react/_auth/Register/Register.scss
- application/react/_global/FormInputs/CustomSelect/CustomSelect.scss
- application/react/_global/FormInputs/Input/Input.scss
- application/react/_global/FormInputs/Input/Input.tsx
This PR handles one main feature and one side quest (should be two PRs, oh well):
1. The main purpose of this PR was to enable SUPER_ADMIN's the ability to assign user's to the roles: `ADMIN`, `USER`. Also allowing them to remove those roles from users.
2. The side quest: redesigning input components, to allow the rendering of leftIcon, leftUnit, rightIcon, rightUnit. This allows us to tell the user visually what an input field is expecting.
To buildout (1) I had to buildout a few new features, such as locking down endpoints to only certain user groups - this allows me to open a new endpoint for updating user roles, that only SUPER_USERs can access.
> Add Ability to Assign/Remove User Roles via UI

- application/react/Material/MaterialForm/MaterialForm.tsx
- application/react/_auth/Login/Login.scss
- application/react/_auth/Login/Login.tsx
- application/react/_global/FormInputs/Input/Input.scss
- application/react/_global/FormInputs/Input/Input.tsx
This PR deals with adding / updating the props: `leftUnit`/`rightUnit`/`leftIcon`/`rightIcon` to the input field Component.
These units/icons are designed to help the user know what values to enter into any given input field.
> Add Input Field / Icons

- application/react/AdhesiveCategory/AdhesiveCategoryForm/AdhesiveCategoryForm.tsx
- application/react/AdminPanel/AdminPanel.tsx
- application/react/CreditTerm/CreditTermForm/CreditTermForm.tsx
- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/Die/DieForm/DieForm.tsx
- application/react/LinerType/LinerTypeForm/LinerTypeForm.tsx
- application/react/Material/MaterialForm/MaterialForm.tsx
- application/react/MaterialCategory/MaterialCategoryForm/MaterialCategoryForm.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- application/react/Vendor/VendorForm/VendorForm.tsx
- application/react/_auth/Login/Login.module.scss
- application/react/_global/FilterBar/FilterBar.module.scss
- application/react/_global/FilterBar/FilterBar.tsx
- application/react/_global/FormErrorMessage/FormErrorMessage.module.scss
- application/react/_global/FormInputs/CustomSelect/CustomSelect.module.scss
- application/react/_global/FormInputs/CustomSelect/CustomSelect.tsx
- application/react/_global/FormInputs/Input/Input.module.scss
- application/react/_global/FormInputs/Input/Input.tsx
- application/react/_global/FormInputs/TextArea/TextArea.module.scss
- application/react/_global/FormInputs/TextArea/TextArea.tsx
- application/react/_global/SearchBar/SearchBar.tsx
- application/react/_styles/button.module.scss
- application/react/_styles/constants.module.scss
- application/react/_styles/table.module.scss
- application/react/_styles/typography.module.scss
- application/svgs/chevron-arrow-down.svg
In this PR, I went from page to page and adjusted any UI styles that stood out. This will be the first of several PRs that finalizes many UI styles. In futures PRs I plan to extract common components into a component library.
> Misc. UI Styling

- application/react/AdhesiveCategory/AdhesiveCategoryForm/AdhesiveCategoryForm.tsx
- application/react/CreditTerm/CreditTermForm/CreditTermForm.tsx
- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/DeliveryMethod/DeliveryMethodForm/DeliveryMethodForm.tsx
- application/react/Die/DieForm/DieForm.tsx
- application/react/Inventory/InventoryFilterBar/InventoryFilterBar.module.scss
- application/react/Inventory/InventoryFilterBar/InventoryFilterBar.tsx
- application/react/LinerType/LinerTypeForm/LinerTypeForm.tsx
- application/react/Material/MaterialForm/MaterialForm.tsx
- application/react/MaterialCategory/MaterialCategoryForm/MaterialCategoryForm.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- application/react/Navbars/Navbar/Navbar.module.scss
- application/react/Navbars/Navbar/Navbar.tsx
- application/react/ShippingLocation/ShippingLocationCard/ShippingLocationCard.module.scss
- application/react/ShippingLocation/ShippingLocationCard/ShippingLocationCard.tsx
- application/react/Vendor/VendorForm/VendorForm.tsx
- application/react/_global/Button/Button.module.scss
- application/react/_global/Button/Button.tsx
- application/react/_global/Dropdown/Dropdown.module.scss
- application/react/_global/Dropdown/Dropdown.tsx
- application/react/_global/FilterBar/FilterBar.module.scss
- application/react/_global/FilterBar/FilterBar.tsx
- application/react/_global/QuickFilterModal/ConditionalQuickFilter/ConditionalQuickFilter.module.scss
- application/react/_global/QuickFilterModal/ConditionalQuickFilter/ConditionalQuickFilter.tsx
- application/react/_global/QuickFilterModal/TextQuickFilter/QuickFilterButton.module.scss
- application/react/_global/QuickFilterModal/TextQuickFilter/QuickFilterButton.tsx
- application/react/_global/SearchBar/SearchBar.tsx
This PR begins a big initiative to convert commonly copy-pasted HTML code into reusable components.
Specifically, this PR adds two new Global components:
1. Button
2. Dropdown
This PR also adds style improvements, mainly to the inventory page, utilizing these new components and custom scss styling
> Global components

- application/react/Address/AddressForm/AddressForm.tsx
- application/react/Customer/Contact/ContactForm/ContactForm.tsx
- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/ShippingLocation/ShippingLocationForm/ShippingLocationForm.tsx
- application/react/User/Profile/Profile.tsx
- application/react/_global/DataTable/DataTable.module.scss
- application/react/_global/DataTable/DataTable.tsx
- application/react/_global/FormInputs/CustomSelect/CustomSelect.tsx
- application/react/_global/FormModal/FormModal.module.scss
- application/react/_global/FormModal/FormModal.tsx
- package-lock.json
- package.json
The focus of this PR was to refresh/refactor the CustomerForm.
This PR does two main things, extract shared logic from that page into a new DataTable component. Update the global `CustomSelect` used in forms to handle multiple selections. Restyle of global `FormModal` which is used several times on that page.
> Redesign/Refactor CustomForm

- application/react/AdhesiveCategory/AdhesiveCategoryTable/AdhesiveCategoryTable.tsx
- application/react/CreditTerm/CreditTermTable/CreditTermTable.tsx
- application/react/Customer/CustomerTable/CustomerTable.tsx
- application/react/DeliveryMethod/DeliveryMethodTable/DeliveryMethodTable.tsx
- application/react/Die/DieTable/DieTable.tsx
- application/react/LinerType/LinerTypeTable/LinerTypeTable.tsx
- application/react/Material/MaterialTable/MaterialTable.tsx
- application/react/MaterialCategory/MaterialCategoryTable/MaterialCategoryTable.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable.tsx
- application/react/MaterialOrder/MaterialOrderTable/MaterialOrderTable.tsx
- application/react/Vendor/VendorTable/VendorTable.tsx
- application/react/_global/Table/TablePageHeader/TablePageHeader.tsx
I noticed that every Table on the site had a searchbar, and some other similar functionality that was copy-pasted into each *Table.tsx component.
So I extracted that into a single, reusable component
> Refactor Tables: Extract Common Repeated Logic into Reusable Component

- application/api/controllers/materialCategoryController.ts
- application/api/models/vendor.ts
- application/react/Address/AddressForm/AddressForm.tsx
- application/react/Customer/Contact/ContactForm/ContactForm.tsx
- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/Customer/CustomerTable/CustomerTable.tsx
- application/react/MaterialCategory/MaterialCategoryForm/MaterialCategoryForm.tsx
- application/react/MaterialCategory/MaterialCategoryTable/MaterialCategoryTable.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable.tsx
- application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx
- application/react/MaterialOrder/MaterialOrderTable/MaterialOrderTable.tsx
- application/react/ShippingLocation/ShippingLocationForm/ShippingLocationForm.tsx
- application/react/Vendor/VendorForm/VendorForm.tsx
- application/react/Vendor/VendorTable/VendorTable.tsx
- cypress/e2e/materialCategory.cy.ts
- cypress/e2e/materialLengthAdjustment.cy.ts
- cypress/e2e/materialOrder.cy.ts
- cypress/e2e/vendor.cy.ts
- cypress/support/commands.ts
- cypress/support/seedTestDatabase.ts
- cypress/support/testData.ts
- test-utils/testDataGenerator.ts
- test/models/materialOrder.spec.js
- test/models/vendor.spec.js
- test/seedTestDatabase.ts
This PR continues the push to rework our cypress integration tests according to best practices.
In this PR, I add cypress tests around the following models:
1. MaterialCategory
2. MaterialLengthAdjustment
3. MaterialOrder
4. Vendor
A majority of the models are now covered, the remainder of the tests will be fairly complex, and thus, gonna save those for the next PR.
> Expand Cypress Coverage (Continued)

- Procfile
- package.json
Running into a too-much-memory-used issue when building heroku
> Fix Heroku Memory Exceeded Issue Preventing Build

- application/react/Customer/CustomerForm/CustomerForm.tsx
- application/react/Die/DieForm/DieForm.tsx
- application/react/Inventory/Materials/Material/MaterialCard.tsx
- application/react/Material/MaterialForm/MaterialForm.tsx
- application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx
- application/react/Vendor/VendorForm/VendorForm.module.scss
- application/react/Vendor/VendorForm/VendorForm.tsx
- application/react/_global/FilterBar/AdvancedFilterDropdown/AdvancedFilterDropdown.tsx
- application/react/_global/FilterBar/QuickSearchDropdown/QuickSearchDropdown.tsx
- test-utils/testDataGenerator.ts
This PR wraps up finishing touches on the following:
1. Adds units next to Form inputs to show user what units the input should be in
2. Add more Quick Filters (one click text searches) and Advanced Filters (Complex/Conditional based filtering)
3. Improves an oversized checkbox that's been bugging me foreverrrrrr
> ELI UX Cleanup

- application/react/_global/Modal/ConfirmationModal.tsx
The last PR removed a datatag which broke an e2e test, thus breaking the ci/cd pipeline.
> Fix Broken e2e Test

- cypress/e2e/inventory.cy.ts
- cypress/plugins/mongodb.js
- test/sharedTestDatabase.ts
This PR updates one of the e2e test responsible for verifying the inventory page, and calculations revolving around that page get computed correctly.
For example, when orders or length adjustments are deleted, inventory calculations should rerun to account for the change - this PR adds that test.
> Improve Inventory E2E Test
