application/middleware/authorize.js, package-lock.json, test/middleware/authorize.spec.js
Currently the build on Heroku is failing, I believe this may be due to an outdate package-lock file being used when installing dependencies.
I deleted and regenerated the package-lock file to hopefully clear this up.
I also encountered code that should have been pushed up in the previously merged PR. I added this to this PR in case it also attributed to the failure.
=> Fix Broken CI/CD Pipeline

package.json
In the last PR #9 Npm/Node versions were specified in the `package.json` incorrectly and allowed for the hosting platform (heroku) to start the application using the latest version of Node (v17) where this app is build on the current LTS version of node (v16)
To resolve this issue, changes were made so heroku can only install Node 16.x.x and no other version.
=> Fix Broken CI/CD Pipeline V3 (lol)

application/index.js
Currently the build on heroku is failing because of a check for a .env file.
The .env file should be present and thus removing this check to see if it remedies the situation.
=> Remove Check for .env as it Does not Play Nicely on Heroku

application/index.js
Heroku fails to load variables defined on the Heroku dashboard which should be accessible via `process.env`.
I am logging the variables I expect are defined to assist with the investigation.
=> Investigate .env issue on heroku

application/controllers/adminController.js, application/controllers/finishController.js, application/controllers/machineController.js, application/controllers/materialController.js, application/index.js, application/models/finish.js, application/models/machine.js, application/models/material.js, application/views/adminPanel.ejs, application/views/createFinish.ejs, application/views/createMachine.ejs, application/views/createMaterial.ejs, application/views/viewFinishes.ejs, application/views/viewMachines.ejs, application/views/viewMaterials.ejs, test/models/finish.spec.js, test/models/machine.spec.js, test/models/material.spec.js
In this PR, new MongoDB objects are introduced (aka new database tables are being added).
These tables are named:
1. Machine
2. Material
3. Finish
Endpoints and UX views were added to handle the CREATION/READING of this data.
Also, an `/admin` endpoint was added which is the location that these 3 tables will be creatable/readable from. Typical users (non-admins) will not be given access to view/modify these objects.
=> Add CREATE/READ Funcationality for New Objects: `Machine`, `Material`, `Finish`

application/views/profile.ejs
An admin panel was previously created by other than a user knowing to visit `\admin`, there were no direct links.
This PR adds a link to the admin panel in the users profile.
**Note:** Actual ADMIN validation has not been added yet, that functionality will come in a later PR. For now, every user will be presented/allowed access to view the admin panel, there are no security vulnerabilities for allowing such an action
=> Add link to previously created admin panel

application/controllers/userController.js, application/views/profile.ejs
An issue existed where a `profile.ejs` front-end view was attempting to display the profile picture for a user, but that data was not available.
The fix was to request the data from the database and hand it off to the `profile.ejs` for display.
=> Fix Issue Profile Picture not Being Displayed Issue

application/controllers/setupController.js, application/views/setupSelection.ejs
Previously, hardcoded values were displayed on the `/setupSelection` page temporarily.
This PR goes through and uses dynamic variables passed from the server in place of these hardcoded values.
=> Feature: pass variable to HTML dynamically to be displayed

application/models/user.js
Previously, when a user would attempt to register, an error occurred preventing the registration.
It turns out, the user object has a non-required field called "username". That field must be unique.
However, a registered user does not need to enter a username yet, therefore the field is null upon registration.
However, since null was indexed and required to be unique, any future user registering was declined since their "null" username was taken already and non-unique.
The fix described [here](https://stackoverflow.com/a/44641358/9273261) was implemented and then I went into mongoDB atlas and manually dropped the existing index which had already indexed null as being a valid/unique username.
If this was confusing to read... just know the problem is fixed 😆
=> Fix Registration Bug

application/controllers/cuttingSetupController.js, application/views/viewCuttingSetups.ejs
Previously, an HTML table existed that displayed many `CuttingSetup` objects from the database.
It was decided that a cool feature would be to allow a user to sort the rows in that table after clicking on any of the column names.
This PR adds the feature that allows a user to sort the table according to any column of their choosing in either `ascending` or `descending` order.
=> Feature: Sort Rows of `cuttingSetup` table on Column Click

application/controllers/windingSetupController.js, application/views/viewWindingSetups.ejs
Previously, an HTML table existed that displayed many `windingSetup` objects from the database.
It was decided that a cool feature would be to allow a user to sort the rows in that table after clicking on any of the column names.
This PR adds the feature that allows a user to sort the table according to any column of their choosing in either `ascending` or `descending` order.
=> Feature: Sort `windingSetup` Columns on Click

application/controllers/printingSetupController.js, application/views/viewOnePrintingSetup.ejs, application/views/viewOneWindingSetup.ejs, application/views/viewPrintingSetups.ejs
Previously a page existed that displayed every `printingSetup` object from the database via an HTML table.
After this PR, you can now click on any row of this table to view all the attributes on their very own page of whichever row was clicked.
=> Add New Page to View any `PrintingSetup` Object Individually 

application/controllers/materialOrdersController.js, application/views/viewMaterialOrders.ejs
Before this PR, every object stored in the `materialOrder` database table would be displayed in a long HTML table.
After this PR, those results are truncated (aka paginated) so only a subset is displayed at any one time.
> After adding pagination to the HTML table
=> Feature: Add Pagination to `materialOrder` Tableview Page

application/views/viewMaterialOrders.ejs
It was desired that the number of feet displayed in this table was calculated based on the formula `materialOrder.totalRolls * materialOrder.feetPerRoll`.
However, it turned out the value was simply `materialOrder.feetPerRoll`, so this PR fixes that.
> The column being updated
=> Fix Incorrect Value Displayed in Table Column

application/controllers/materialOrdersController.js, application/views/viewMaterialOrders.ejs, application/views/viewOneMaterialOrder.ejs
Previously a table existed that displayed all `materialOrder` objects displayed in the database.
This PR adds the ability for a user to "Click into" one of those objects and see additional information for only that object
> Newly added page, **NOTE** the page will be CSS styled in a future PR
=> Feature: Add Page to Display Details about ONE `materialOrder` Object

application/controllers/materialOrdersController.js
Previously two API endpoints existed `GET material-orders/:id` and ` GET material-orders/create`.
However, it was learned that the order of these endpoints maters, since :id will take in any value following `material-orders/*` and be a match, therefore, the fix for this was to move `GET material-orders/create` above the other endpoint in the code so it is selected first.
Note: There's probably a better way to go about naming/placing these api endpoints, but this is fine for now.
=> Fix Routing Issue

application/controllers/ticketController.js, application/models/ticket.js, application/public/js/main.js, application/services/userService.js, application/views/updateTicket.ejs, test/models/ticket.spec.js, test/services/databaseService.spec.js
A `TICKET` object is composed of many PRODUCTs. Each `PRODUCT` has a primaryMaterial attribute.
It was desired that this primaryMaterial attribute also be included on the TICKET object, and further, any updates to the TICKET.primaryMaterial need to overwrite all primaryMaterials stored on the PRODUCT objects.
This PR does all those things
=> Add `primaryMaterial` to TICKET Object

application/controllers/productController.js, application/models/product.js, application/services/s3Service.js, package-lock.json, package.json, test/models/product.spec.js
Previously, a user was allowed to upload a PDF representing a "proof" into the MongoDB database.
However, MongoDB limits the size of each document to 18MB, therefore, any PDF uploaded which is over 18MB results in an exception.
This PR fixes that issue by instead shipping those PDFs to an AWS S3 bucket and only storing that resulting S3 object URL in MongoDB 🎊 
Pretty cool eh?!
=> Store Proof PDFs in AWS S3 Bucket

application/controllers/ticketController.js, application/services/ticketService.js, application/views/viewTickets.ejs, test/services/ticketService.spec.js
Previously, there was a UI View that displayed a single table with every Ticket object listed
Each of those ticket objects has an attribute called "department" and it was decided that the UI View should display many tables, with each view displaying the tickets for a specific department.
The end result is a list of 10 HTML tables, where each table represents the tickets for each of the following departments:
1. `IN PROGRESS`
2. `ORDER PREP`
3. `ART PREP`
4. `PRE-PRESS`
5. `PRINTING`
6. `CUTTING`
7. `WINDING`
8. `SHIPPING`
9. `BILLING`
10. `COMPLETE`
=> Feature: Group Tickets by Department

application/controllers/materialInventory.js, application/controllers/materialOrdersController.js, application/index.js, application/services/materialInventoryService.js, application/services/materialOrderService.js, application/services/socketService.js, application/views/partials/navbarMain.ejs, application/views/updateMaterialOrder.ejs, application/views/viewMaterialInventory.ejs, package-lock.json, package.json, test/services/materialInventoryService.spec.js, test/services/materialOrderService.spec.js
The main thing this PR does is add a new view `/material-inventory` page (file `viewMaterialInventory.ejs`).
This page displays the length of materials that have been purchased (aka `materialOrder` objects, also known as `purchaseOrder` objects - the terms are used interchangably).
This page is meant to be viewed in order to determine how much (in feet of length) material has been ordered and how much of it has arrived and is sitting in inventory.
sockets were used thoroughly in this PR in order to update values displayed on `/material-inventory` without the need for a page refresh. See the video in this descriptions "verification" section to see those real-time updates in action.
> New view `/material-inventory` page was added in this PR. Also, websockets were used to make data on that …
=> Add `Material Inventory` Page

application/controllers/materialInventory.js, application/services/materialInventoryService.js, application/services/materialOrderService.js, test/services/materialInventoryService.spec.js, test/services/materialOrderService.spec.js
After merging #110 it was noticed that all purchaseOrders were being displayed on the `/material-inventory` page for each material.
It was decided that only purchaseOrder objects whose attribute `hasArrived = false` should be displayed.
This PR fixes that issue.
Also, a mis-formatted error message was also uncovered and fixed with a line of code
=> Minor Functionality Bug Fixes

application/controllers/ticketController.js, application/enums/idToColorEnum.js, application/models/product.js, application/models/ticket.js, application/public/js/main.js, application/services/ticketService.js, application/views/updateTicket.ejs, test/models/product.spec.js, test/models/ticket.spec.js, test/services/ticketService.spec.js
@LifeByStorm determined that several attributes on `Ticket` and `Product` objects had not yet been added to their respective database schemas. This PR handles adding those attributes, as well as writing validation rules around each.
Also, `printingType` was previously allowed to be set via a front-end dropdown menu, but that is no longer the case, and instead, its value is uploaded manually via the Ticket XML uploads.
Some minor validation rule changes were also found on some pre-existing attributes and were updated in this PR.
=> Add/Update Attributes and Validations Around `Ticket` and `Product` Database Objects

application/models/product.js, test/models/product.spec.js
This PR updates the attribute `prePrintingNotes`.
It was determined that the datatype of this attribute was invalid and this PR fixes the issue.
=> Update Attribute  `prePrintingNotes` on `product` Object

application/views/viewTickets.ejs
Every ticket object in the database has a `products` attribute. That attribute is an array of product objects...duh.
We wish to display a ticket's products on the page `viewTickets` dynamically.
This PR adds javascript onto the .ejs template to dynamically generate a row representing a product for every ticket displayed on the `viewTickets` page
Note: The data shown for each product is still a placeholder, that will be updated in a later PR.
> Now all products on a ticket are displayed beneath the ticket
=> Dynamically Display All Products for each Ticket on `viewTickets.ejs`

application/enums/priorityEnum.js, application/models/charge.js, application/models/cuttingSetup.js, application/models/finish.js, application/models/machine.js, application/models/material.js, application/models/materialOrder.js, application/models/printingSetup.js, application/models/product.js, application/models/recipe.js, application/models/ticket.js, application/models/user.js, application/models/vendor.js, application/models/windingSetup.js, test/models/charge.spec.js, test/models/product.spec.js, test/models/ticket.spec.js, test/models/user.spec.js, test/models/windingSetup.spec.js
This PR ensures that any string attribute stored in the mongDb database has its leading and trailing whitespace removed prior to being saved.
This trim functionality is offered as a [configuration rule in mongoose](https://thecodebarbarian.com/whats-new-in-mongoose-59-schematype-default-options-and-per-document-populate.html).
After this PR, any string attributes added to any of the existing database tables will be trimmed by default.
=> Trim Leading/Trailing Whitespace on ALL String Attributes Before Saving to Database

application/services/chargeService.js, test/services/chargeService.spec.js
Currently, a user can upload an XML file that contains an array of `products`.
However, sometimes one or more of these products is actually a different object called a `charge`.
These charge items need to be manually removed from the products array and previously code was added to do this, however, a bug was discovered with that code, and this PR fixes that bug and adds tests to prevent it from happening again.
=> Remove `Charge` Objects During XML File Upload

application/models/product.js, test/models/product.spec.js
The `varnish` attribute (aka _ColorDescr_) is uploaded via an XML file as a string.
That string contains the prefix "C:".
We don't want to save this prefix to the database, instead, we need to remove it before saving it to the database.
This PR handles doing that.
=> Update `Varnish` Attribute on `PRODUCT` Object

application/models/ticket.js, test/models/ticket.spec.js
Currently on a `Ticket` object, a user is allowed to defined a `subDepartment` and a `department`.
The department a user defines must be one string from a list of allowed strings.
Then, based on which department the user selects, the user must select an allowed subDepartment from a list.
The allowed subDepartments are dependent on which department the user has selected... However, I discovered that this validation rule was not enforced.
This PR adds a test case and updates the validation to cover this scenario.
=> Add Department/SubDepartment Validation Rule

application/controllers/ticketController.js, application/enums/departmentsEnum.js, application/models/WorkflowStep.js, application/models/ticket.js, application/public/css/main.css, application/public/js/main.js, application/services/ticketService.js, application/views/updateTicket.ejs, application/views/viewOneTicket.ejs, application/views/viewTickets.ejs, test/enums/departmentsEnum.spec.js, test/models/ticket.spec.js, test/models/workflowStep.spec.js, test/services/ticketService.spec.js
It was determined that the naming `subDepartment` throughout the code was not technically valid and was misleading.
Instead, it was determined that a better name was `DepartmentStatus`.
> After changing the column name on the database table, all the old data essentially become outdated and no tickets which existed before appear on this page. This is because the old tickets have  a `subDepartment` attribute instead of the new `departmentStatus` attribute. This old data is not important so no migration will occur.
> After uploading a new ticket and setting its the `department` and new `departmentStatus` attribute, it is displayed correctly in the table
=> Rename all Usages of `SubDepartment` to `DepartmentStatus`

application/models/WorkflowStep.js, application/models/destination.js, application/models/ticket.js, test/models/destination.spec.js, test/models/ticket.spec.js, test/models/workflowStep.spec.js
Previously there were 2 NO-SQL database tables named `Ticket` and `WorkflowStep`.
On these two tables, there were shared attributes, namely `department`, `departmentStatus`, `assignees`, `machines`.
Instead of duplicating these attributes and their validations across these two tables, instead I decided to extract that duplicate logic into a new mongoose schema called `destination` and then reference that schema on both database tables.
The second thing this PR does is creates a new item in the `WorkflowStep` table IF a `Ticket` object has either of the `department` or `departmentStatus` attributes updated.
After performing an update to a `Ticket`'s department/departmentStatus attribute, a new item is injected into the database table `workflowStep`
> Update to `Ticket`'s …
=> Track Changes to a Ticket Object's `department`/`DepartmentStatus` Attributes

application/models/product.js, application/views/viewOneProduct.ejs, test/models/product.spec.js
This updates 2 product level attributes and updates those attribute's validation rules. The attributes are:
1. product.coreHeight
2. product.numberOfCores
This PR also updates how the attribute product.coreHeight is displayed on the UI. Previously it was displayed as a decimal between 0 and 1. Instead, we wish to display it as a percentage, so this PR makes that change.
> This screenshot shows the 3 attributes after my changes
=> Add/Update `PRODUCT` Attributes and Validation Rules

application/views/viewTickets.ejs
Previously, two buttons existed on the UI which did nothing when clicked:
This PR adds `href`s to those buttons to make them link to the correct pages
> Clicking "View Ticket" takes the user to the appropriate page
> Clicking "Update Ticket" takes the user to the appropriate page
=> Make "View Ticket" and "Edit Ticket" Buttons work within `viewTickets.ejs`

application/services/workflowStepService.js, test/services/workflowStepService.spec.js
Previously I had written code that looped over values in an array, and for each value, a unique HTTP request was sent to the cloud database to query for data.
Each of these HTTP requests has a small amount of latency to send the request and receive the response.
This was dumb, and scales horribly, especially when the front-end page is stuck loading until all the requests have been sent and received.
The fix for this was to perform one HTTP request, which contained the array of attributes I wished to query, and then perform logic on the server to parse and format the results in the way I needed.
Before making these changes, I timed how long the N number of HTTP requests took to complete. I timed this 10 times and the average result was `494.994 ms`.
After making these changes, I timed the …
=> perform batch db query to improve performance

application/public/js/main.js, application/services/ejsService.js, application/views/viewTickets.ejs
On the frontend, a list of tickets are displayed in various tables.
Each ticket has an option to `move` a ticket to a different table on the same page.
This PR makes that `move` functionality work and utilizes ajax to persist that moved state.
The functionality for making the ticket disapear from the table it's currently in and reappear in the table it is being moved to is coming in a future PR.
> The correct `departmentStatuses` are displayed when the `order-prep` department is selected
=> Feature: Make Tickets Movable

application/controllers/ticketController.js, application/public/js/main.js, application/views/partials/department-status-clones.ejs, application/views/viewTickets.ejs
This PR is a wip and my plan is to move it partially completed for reasons.
This PR allows a user to move a ticket from one departmentStatus to another departmentStatus.
Previously this could be done on the UI, however the user needed to refresh to see the ticket move on the UI to its new departmentStatus.
This PR does a ton with html/css/js in order to make the ticket move on the UI to the new departmentStatus without the user needing to refresh the page.
A user can now select a ticket with `departmentStatus A` and choose to move that ticket to `departmentStatus B` and the ticket will be removed from `Table A` and appear on `Table B`.
The areas on the UI that display how many tickets are in each table is updated dynamically, and in the event that the moved ticket now makes `Table A` …
=> Feature: Make `Move` Tickets Work

application/public/js/main.js, application/views/viewTickets.ejs
Currently, one page `viewTickets.ejs` contains many various HTML tables, each table has many rows.
A user is able to move a row from one table to another via UI interactions, however, prior to this PR, the row numbers shown would not be updated during the move.
This PR now refreshes all row numbers in ALL tables after any move occurs.
> Before
> After
=> Feature: Update Ticket Row Numbers After a Ticket is Moved

application/public/js/main.js, application/views/partials/department-status-clones.ejs, application/views/partials/product-clone.ejs, application/views/partials/products-wrapper.ejs, application/views/viewTickets.ejs
Currently the view `viewTickets.ejs` has many tables, each table has many rows. Each row represents a ticket. Each row is clickable, and on click, the products associated with that Ticket are displayed as rows below it.
This functionality was working great, but when tickets were moved from table to table on this view, the injected ticket row was not clickable due to jquery reasons.
This PR makes jquery updates such that the moved ticket rows are still clickable and on-click, the products associated to that ticket are dispalyed as rows below it.
> Tickets are still clickable after being moved ✔️
=> Populate product rows on moved ticket

application/public/js/main.js, application/views/partials/products-wrapper.ejs, application/views/partials/start-job-modal.ejs, application/views/partials/ticket-dropdown-options.ejs, application/views/viewTickets.ejs
Prior to this PR, when a ticket is moved from one departmentStatus table to another departmentStatus table, that "move" was done via jquery.
However, after injecting the element with jquery, many attributes on that injected row are not dynamically set and need to be.
This PR takes a step in the direction of populating the many attributes that need to be set dynamically, more PRs need to be done to fully finish this feature.
=> Wip: Dynamically Populate HTML Attributes on Moved Ticket

application/public/js/main.js, application/views/partials/product-clone.ejs
Previously when a ticket was moved from one department to another, a bunch of jQuery made that move happen without the need of a refresh.
However, some links on the moved ticket were not updated to work, which includes a "view product" button.
This PR fixes the href on that button to make it link correctly utilizing jQuery.
> Clicking this button now calls the `GET /products/:id` endpoint
=> Feature: Make 'view product' Button Work

application/public/js/main.js, application/views/partials/product-clone.ejs
Prior to this PR, when a ticket was moved from one departmentStatus into another departmentStatus, the information on the products for that ticket were not dynamically populated.
This PR dynamically populates those products using jquery/js.
> After a ticket is moved, the product rows are now dynamically populated
=> Feature: Dynamically Populate Product Rows after Ticket is Moved

application/controllers/ticketController.js, application/public/js/main.js, application/views/partials/ticket-dropdown-options.ejs
Previously, every row in a table had a dropdown called "duration" which was populated on page refresh.
The calculations required to populate this "duration" for every row in the table on refresh slowed down the page and the calculation itself took 150ms which made up a vast majority of the 250ms it took for the page to load.
Instead of that, I refactored in this PR and do not populate the dropdown "duration" on page load, instead, I only  fetch that information if the user hovers their mouse over "duration" and then I use AJAX to fetch and populate that hovered "duration".
After these changes, the page `viewTickets.ejs` now loads in 100ms versus before it took 250ms to load. Heck yeah!!!
=> Refactor: Only Query for Duration Info when User Hovers Element

application/controllers/ticketController.js, application/enums/departmentsEnum.js, application/models/destination.js, application/public/js/main.js, application/services/ticketService.js, application/views/partials/start-job-modal.ejs, application/views/viewOneInProgressTicket.ejs, application/views/viewTickets.ejs, test/enums/departmentsEnum.spec.js, test/models/destination.spec.js, test/models/ticket.spec.js, test/models/workflowStep.spec.js, test/services/ticketService.spec.js, test/services/workflowStepService.spec.js
This PR does a couple things (woops).
1. Adds a new view called `viewOneInProgressTicket.ejs` which is rendered when a user selects `Start Ticket` via a modal on `viewTickets.ejs`
2. Updates the departmentStatuses that a ticket can be moved to. The list of acceptable departmentStatuses a ticket can be moved to are found in `departmentsEnum.ejs`
3. Ensures that a user cannot manually set an "IN PROGRESS" departmentStatus on a ticket, this is only allowed to be done programmatically
Previously a `TICKET` mongoDb object was only allowed to have specific strings (an enum) set onto it's `destination.department` and `destination.departmentStatus` attributes.
It was recently brought up that this list of strings needed to change, so this PR makes that change.
The list of strings that can be set …
=> View in progress ticket

application/public/js/main.js
Recently HTML was changed which included and css class names on that HTML were changed or rearranged.
This broke some jquery that relied on the deleted/updated css classes for its selectors.
This PR updates the selectors to get that stuff working again.
=> Update Jquery Element Selectors After Recent HTML Changes

.circleci/config.yml
CircleCi is a CI/CD pipeline tool that can be configured in a github project by adding a the following folder and file: `.circleci/config.yml`. Once this is added to the project, the project is automatically viewable/manageable from the circleCi website via a dashboard: https://app.circleci.com/pipelines/github/gavinvaske/the_recipe_book
I configured the .yml file such that, all the tests and linter run every time a commit is made to a PR, aka `npm run verify` executes
=> Add CircleCi CI/CD pipline to Handle Running Tests on PRs

application/models/destination.js, application/models/product.js, test/models/destination.spec.js, test/models/product.spec.js
It was determined that the attribute "machines" which previously lived on `destination` schema was no longer required, and thus it was removed in this PR.
Also, seperately, I updated the validation rules to allow for the attribute `product.productDie` to allow for the string "Press Proof". Previously, this string would fail validation, but now it is allowed.
=> Update Schema Validation Rules on `Product`/`Destination` Objects

application/models/destination.js, application/public/js/main.js, test/models/destination.spec.js, test/models/workflowStep.spec.js
This PR does 2 things:
1. Reverts one commit from #206 that removed the "machines" attribute from the mongoose `destination` schema
2. Converts the `machines` attribute and `assignees` attribute on the mongoose `destination` schema to their singular equivalent
=> Update Attributes on `Destination` Schema

application/models/ticket.js, application/public/js/main.js, application/views/viewTickets.ejs, test/models/ticket.spec.js
This PR does 2 things:
1. It adds a newly "calculated" attribute to the `Ticket` mongoose schema called `totalMaterialLength`. Each ticket has a different attribute called `products` which is an array of objects. Each of those products has an attribute called `totalFeet`. The attribute `totalMaterialLength` is a summation of each product.totalFeet. (**Formula:** ticket.totalMaterialLength += ticket.products[n].totalFeet)
2. This PR changes a lot of the column names in the 37 html tables that live in `viewTickets.ejs`. Many of the column names in that file were outdated, and this PR makes them up to date with the data they are going to store.
=> Add attribute: `ticket.totalMaterialLength` and Update Column Names in `viewTickets.ejs`

application/models/ticket.js, test/models/ticket.spec.js
It was determined that there are 2 dates that are important to persist called `sentDate` and `followUpDate`. These 2 date attributes are used to determine when certain events occurred during a `ticket` object's lifecycle.
This PR adds those 2 attribute via mongoose schema definitions, and also adds tests.
=> Add 2 Attributes to `Ticket` Schema: `sentDate` and `followUpDate`

application/models/holdReason.js, application/models/ticket.js, test/models/holdReason.spec.js, test/models/ticket.spec.js
This PR defines a new mongoose database schema called `HoldReasons`. This database table will be used by the application in future PRs to persist user-defined "hold reasons" - but at the moment, this table is not in use.
This PR also adds a new attribute to the `ticket` schema called `holdReasonByDepartment`. This attribute is essentially a javascript object (technically its a javascript map).
=> Add `HoldReasons` Database Table and Add `ticket.holdReasonByDepartment` Attribute

application/public/js/main.js, application/views/partials/follow-up-date-picker.ejs, application/views/viewTickets.ejs
Previously, a datepicker was added to the user interface that allowed the user to select a date.
However, the selected date did not persist to the database and thus, on refresh, the date disappeared.
This PR saves the data they select and handles fetching it again on page refresh so the date stays.
> After page refresh, the date the user had  previously selected still exists
=> Save `ticket.followUpDate` to Database after User Selects a Date on the UI

application/controllers/holdReasonController.js, application/controllers/ticketController.js, application/index.js, application/models/holdReason.js, application/models/ticket.js, application/public/js/main.js, application/services/holdReasonService.js, application/views/partials/follow-up-date-picker.ejs, application/views/partials/on-hold-dropdown-option.ejs, application/views/partials/on-hold-dropdown.ejs, application/views/viewTickets.ejs, test/models/holdReason.spec.js, test/models/ticket.spec.js, test/services/holdReasonService.spec.js
Currently, there exists a part on the UI in which we want a user to be able to choose one option from a list of "hold reasons".
Their selected "hold reason" then needs to be stored in the database.
This PR populates the list of "Hold Reasons" that the user can select from. These "Hold Reasons" are user-defined and are stored in a mongoose table called `HoldReasons`.
> User can type in a "Hold Reason" to add and click the button
> Upon adding the "Hold Reason" it is added to the HTML list
> Upon selecting the added "Hold Reason" it populates the column of the row
=> Allow user to Create/Set a `holdReason` on a `Ticket` object

application/views/viewTickets.ejs
The `viewTickets.ejs` page would throw an ejs error and not load in some scenarios with a error message saying that `.get()` could not be called on an `undefined` variable. This PR should resolve that issue.
=> Fix Issue Where Trying to Access '.get()' on Null Variable

application/models/ticket.js, application/models/ticketGroup.js, test/models/ticket.spec.js, test/models/ticketGroup.spec.js
Currently there is a database table called `tickets`. The need for each ticket to be able to store a reference to other tickets was brought up.
This PR adds a new attribute (`ticket.ticketGroup`) which provides the ability for a group of tickets to be stored on each ticket.
=> Add `ticket.ticketGroup` Attribute

application/views/partials/ticket-table.ejs
An ejs error was crashing viewTickets.ejs, it turns out a parital was not getting the template attributes it required to render, this PR resolves that issue.
=> Fix EJS Bug that was Crashing `viewTickets.ejs` page

application/controllers/ticketController.js, application/services/dateTimeService.js, application/services/ejsService.js, application/views/partials/ticket-table.ejs, test/services/dateTimeService.spec.js, test/services/ejsService.spec.js
There are columns in tables on the viewTickets page that we wished to format such as "01 February".
This PR makes that happen
> The column now displays dates in the correct format
=> Feature: Format Date Columns on `viewTickets.ejs`

.circleci/config.yml, application/controllers/holdReasonController.js, application/models/holdReason.js, application/public/js/main.js, application/services/holdReasonService.js, application/views/partials/on-hold-dropdown-option.ejs, application/views/partials/on-hold-dropdown.ejs, package-lock.json, package.json, test/models/holdReason.spec.js, test/models/ticket.spec.js
This PR adds the library [mongoose-delete](https://www.npmjs.com/package/mongoose-delete) which overrides many/most of the mongoose methods in order to handle soft delete items and query only items that have not been soft deleted.
In short, this library adds an attribute called `delete = true` to any item which has been deleted, after which, when using mongoose's method `find()` or another one of the similar find methods it offers, it will only return items whose `delete` field is not defined or false, any rows whose delete attribute is true will be excluded from the results.
However, this library provides many additional methods for specifically querying for delete attributes.
There is an entire table showing the mongoose methods that this library overrides or adds, you can find it …
=> Implement Soft Deletions

application/controllers/ticketController.js, application/enums/departmentsEnum.js, application/services/dateTimeService.js, application/services/workflowStepService.js, application/views/viewOneInProgressTicket.ejs, test/services/workflowStepService.spec.js
Prior to this PR, there was a view that was rendered when a user visited `/tickets/in-progress/:ticketId` which showed information about the ticket associated in the database to the `:ticketId`.
This page was mostly hardcoded and styled, but this PR makes the hardcoded parts dynamic. All values seen in the screenshot below are dynamically rendered.
> Attributes now populate dynamically on this view
=> Dynamically Populate Fields on `/tickets/in-progress` View

application/controllers/ticketController.js
A recent PR broke an endpoint that allowed users to upload a file and that file would be converted to a `ticket` object in the database.
This PR fixes that issue and makes everything work again.
=> Fix Broken Ticket Upload Endpoint

application/controllers/materialInventoryController.js, application/services/materialInventoryService.js, application/services/materialService.js, application/services/mongooseService.js, application/services/ticketService.js, application/views/viewMaterialInventory.ejs, package-lock.json, package.json, test/services/materialInventoryService.spec.js, test/services/materialService.spec.js, test/services/mongooseService.spec.js, test/services/ticketService.spec.js
This PR does a pretty cool thing in my opinion.
Currently, this application allows users to store Purchased Material ("purchaseOrders"). This application also allows users to use part of the materials that were purchased. The amount used is stored on a ticket database object, specifically the attribute called `ticket.lengthUsed`.
The need for computing the "net" amount of material available was brought up, and this PR makes that happen.
The formula for the net material available is `Sum(purchaseOrder) - Sum(materialUsedByTickets) = Net Material Sitting in inventory`)
> The net amount of material available is displayed on the `/material-inventory` page
=> Feature: Compute Net Material Usage on Inventory Page

application/public/js/socket-event-listeners.js, application/services/socketService.js
This PR removes the websocket functionality from the `/material-inventory` page until issue #258 is completed.
The completion of that issue will bring this functionality back
=> Comment out `/material-inventory` Web Sockets

application/enums/departmentsEnum.js, application/models/ticket.js, application/schemas/departmentNotes.js, test/models/ticket.spec.js, test/schemas/departmentNotes.spec.js
This PR mainly adds/updates attributes on the mongoose `ticket` table.
1. `departmentToJobComment`: This is a brand new field whose purpose is to store notes added by a user after they completely finish their work in a specific department
2. `attempts`: This is a brand new attribute whose purpose is to store the number 50 foot frames used when completing a ticket. This attribute is used by the field `totalMaterialLength` such that `totalMaterialLength = totalMaterialLength + (attempts * 50)`
3. `totalMaterialLength`: This field existed before, but now, I changed how this field is calculated. When a user attempts to set it after this PR is merged, an extra calculation will also be applied to it: totalMaterialLength = totalMaterialLength + (attempts * 50).
This PR also does some …
=> Add/Update Ticket Attributes: `departmentToJobComment`, `totalMaterialLength`, `attempts`

application/models/downtimeLedger.js, application/models/downtimeReason.js, application/models/ticket.js, application/schemas/charge.js, test/models/downtimeLedger.spec.js, test/models/downtimeReason.spec.js, test/schemas/charge.spec.js
This PR creates two new mongoose database table:
1. `downtimeReason`
2. `downtimeLedger`
Currently, it is important that the system tracks the total amount of time that a ticket spends in production.
These database table allow for users/employees to enter the amount of time that a ticket was delayed, and the reason for which the delay occurred.
=> Add new Mongoose Table: `downtimeReason`

application/controllers/materialController.js, application/models/material.js, application/views/createMaterial.ejs, application/views/updateMaterial.ejs, test/models/material.spec.js
This PR adds a new attribute to the `material` mongoDb database table called `materialCategory`.
This attribute references items from the `materialCategory` (relationships in a noSql database, *gasp* 😉 ).
This PR also updates the UI pages responsible for Creating/Updating this attribute.
> New selection added to material `Create` page
> New select added to material `Update` page
=> Add New Database Attribute: `material.materialCategory`

application/models/material.js, test/models/material.spec.js
This PR updates the mongoose schema on material.name such that any string used is set to uppercase by default.
=> Feature: Make `material.name` Uppercase by Default

application/public/js/search-and-filtering.js, application/views/layout.ejs, application/views/partials/tableColumns/date-picker-column.ejs, application/views/partials/tableColumns/hold-reason-column.ejs, application/views/partials/tableColumns/text-column.ejs, application/views/partials/tableColumns/user-column.ejs, application/views/partials/ticket-workflow-sorting-filtering.ejs
Currently there exists a UI page (viewable at `${baseUrl}/tickets` that renders 37 HTML-like tables.
Each table has unique columns.
We wish to make all of these tables searchable via a searchfield that the user may type into, and only rows that match the search should be shown.
At first look, this was a crazy complex problem, but the following is the solution I settled on.
Bonus: This functionality also works with the tables on the `${baseUrl}/requests` page
Using jquery, my "sudo" code is as follows:
When user types in a search query, then convert each row of every table into a single string of searchable text.
Compare the user's search query against this big string (i.e. using javascript's `.includes()` method.
If that row is not a match, hide it.
It wasn't quite that simple, since if …
=> Feature: Make Data in UI Tables Searchable

terraform/main.tf
A PR was recently merged that created a brand new S3 bucket to store user uploaded files (technically an old one existed prior to that which but was deprecated and will be deleted soon).
This new bucket however did not have public access rights, so if a user attempted to download a file from that bucket, they were denied access. This PR provides public read access to that bucket.
=> Feature: Enable Public Access to S3 so Users can Download their Uploads

application/controllers/ticketController.js, application/public/js/main.js
There's an endpoint that is called to make a attribute-level update to an object. The endpoint should use the `PATCH` HTTP verb to abide by RESTful best practices. Also verbs in an RESTful endpoint are 🤮 
This PR makes those changes
=> Convert `POST` endpoint to `PATCH`

application/public/js/main.js, application/views/viewTickets.ejs
Previously a bar used to filter groups of objects based on a common attribute was broken.
The root issue was an a few div elements that were missing a closing </div> tag which resulted in sneaky jquery bugs.
The fix was to add those closing tags back in.
=> Fix Ticket Filter Bar

application/controllers/filePlanController.js, application/services/filePlanService.js, test/services/filePlanService.spec.js
A previous PR merged filePlan logic.
After checking that over, it was asked that one more attribute be added to that data.
This PR adds that attribute
New attribute is added on fileplan:
=> add `filePlan.originalFrames` attribute

application/services/databaseService.js, package-lock.json, package.json, test/models/baseProductSnapshot.spec.js, test/services/databaseService.spec.js
Mongoose is currently on version 8+
This PR makes the major update from V7 to V8, adheiring to their migration guide.
Luckily their breaking changes impacting almost nothing
=> Upgrade Mongoose `V7` to `V8`

application/react/_global/Modal/Modal.tsx
When user clicks the dark background of a modal, close the modal.
In addition to allowing a user to click on the X button.
=> `Q of L`: Close `Modal` Component on Background Clicked

.vscode/extensions.json, application/react/tsconfig.json, application/tsconfig.json, cypress/tsconfig.json, tsconfig.base.json
This PR adds tsconfig.json to the API directory and UI directory
These configurations tell the built in typescript compiler within `parcel` (the "bundler" this repo uses) so we can start getting helpful errors
=> Add `tsconfig.json` for API and UI

package-lock.json, package.json, test/models/material.spec.js
Using this PR to upgrade mongodb-memory-server
I found that only minor version upgrades work, but in the circleci CI/CD pipeline, any major version updates fail there (but work locally, naturally..)
If flaky tests arrive again (and they will) around saving duplicate unique db properties:
Look into the following:
SomeModel.syncIndex()
mongoose.syncIndexes()
=> Upgrade `mongodb-memory-server`

application/react/_auth/ProtectedRoute/ProtectedRoute.tsx, application/react/_hooks/useRefreshToken.ts
In some situations, like not having logged into the site for awhile.
When I tried to navigate to a "ProtectedComponent" a pre-check would occur. Part of this pre-check is to attempt to refresh the user's accessToken via their refreshToken (stored on the server securely 😉 )
However, the situation for handling an expired, or non-existant refreshToken was never handled correctly via the UI.
The server returns a 403 status error when this occurs, but the front-end wasn't handling this error and redirecting the user to the login page correctly. So instead, it attempted to refresh their access token over-and-over-and-over-and....
This PR fixes that
=> Fix Bug Causing Infinite Loop

application/api/models/baseProduct.ts, application/react/Customer/Contact/ContactForm/ContactForm.tsx, application/react/Customer/CustomerForm/CustomerForm.tsx, application/react/Die/DieForm/DieForm.tsx, application/react/Product/ProductForm/ProductForm.tsx, application/react/Quote/InputSection/DieInput/DieInput.tsx, application/react/_global/FormInputs/CustomSelect/CustomSelect.scss, application/react/_global/FormInputs/CustomSelect/CustomSelect.tsx, application/react/_global/FormInputs/Input/Input.tsx, application/react/_global/FormInputs/TextArea/TextArea.tsx, test/models/baseProduct.spec.js
Previously, we had two custom components setup and integrated with react-hook-form:
`<Input .../>`
`<Select .../>`
Whenever we were creating a form that required a large amount of user text, we just used the Input component.
However, it was determined that, we instead needed a `<TextArea .../>` component so we could show multiple lines.
It was also determined that we could/should not use the default HTML <select ... /> which is exactly what the wrapper component <Select .../> was doing under the hood.
This was due to <select being pretty hard/in-flexible to apply custom styles to
So this PR adds a new component `<CustomSelect />` that rebuilds the select field, without using HTMLs <select (it was not easy lol)
=> Add `CustomSelect` and `TextArea` Component

application/react/User/Profile/Profile.tsx
There was an issue when the following happened:
1. a user visited their profile page
2. the user navigated to another page by clicking a button on the navbar
3. a user navigated back to their profile via the navbar
When (1) a user would see a populated profile form on their profile page, with stuff like their name, birthdate, ect
When (3) the form would be empty
This PR fixes (3)
=> `react-query` Bug Fix

package.json
There's an error on heroku that occurs when the parcel build is attempted to be cached. This is likely an operation denied by heroku - potentially because of the directory parcel is attempting to store the cache being protected.
This PR (for now) disables the parcel cache.
=> Fix: Don't Cache Parcel Build

application/api/controllers/materialLengthAdjustmentController.ts, application/api/models/materialLengthAdjustment.ts, application/react/App/App.tsx, application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx, application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentRowActions/MaterialLengthAdjustmentRowActions.tsx, application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable.tsx, application/react/Quote/QuoteTable/QuoteTable.tsx, application/react/_queries/materialLengthAdjustment.ts
This PR updates the UI and API to allow for the Creation, Update, and Deletion of Material Length Adjustment objects
I verified that, from the inventory page, a user can click "create adjustment" and get routed to the CREATION page.
Once they create a material length adjustment, they are routed to a TABLE listing all.
From the table, they can edit or delete via a "row actions" button
=> Material Length Adjustments CRUD

application/api/controllers/materialController.ts, application/api/controllers/materialLengthAdjustmentController.ts, application/api/controllers/materialOrdersController.ts, application/api/controllers/productController.ts, application/api/controllers/quoteController.ts, application/api/models/material.ts, application/react/Material/MaterialForm/MaterialForm.tsx, application/react/Material/MaterialForm/MaterialLocationSelector/MaterialLocationSelector.scss, application/react/Material/MaterialForm/MaterialLocationSelector/MaterialLocationSelector.tsx, application/react/_types/databaseModels/material.ts, test/models/material.spec.js, test/testDataGenerator.ts
This PR adds the attribute `material.locations`. The idea behind this attribute is operators can select where a material is currently at, such as: `C1`, `Z22`.
This PR also updates the create/edit material UI pages to enable setting this value
=> Add material.locations 

application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentTable.tsx, application/react/_utils/dateTime.ts
Previously we had dates and dateTime columns that were not being formatted.
I.e:
`2022-04-18T23:51:56.714Z`
`2025-10-25`
`ect`
were being printed
This PR adds helper methods such that:
1. Dates are formatted as: `Dec 30, 2027`
2. DateTimes are formatted as: `Dec 01, 2023, 10:50 AM`
=> Format Columns in Table

application/api/controllers/authController.ts, application/react/axiosHelpers.ts
Previously there was a bug, where if a refresh token became expired - the frontend would still continue to send requests refresh an access token using it.
Ideally, instead of that, the user is redirected back to the login page to get a new refresh token / access token.
That is what this PR does.
=> Fix Login Bug

application/react/Customer/Contact/ContactForm/ContactForm.tsx, application/react/Customer/CustomerForm/CustomerForm.tsx, application/react/Die/DieForm/DieForm.tsx, application/react/Material/MaterialForm/MaterialForm.tsx, application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx, application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx, application/react/Vendor/VendorForm/VendorForm.tsx, application/react/_global/FormInputs/Input/Input.tsx
This PR does two things:
1. Adds a `unit` prop to `Input` component to tell users what the field units are
2. Converts 'note' attributes from `Input` components to `TextArea` components
=> Add Units to Input Fields

application/react/AdhesiveCategory/AdhesiveCategoryForm/AdhesiveCategoryForm.tsx, application/react/CreditTerm/CreditTermForm/CreditTermForm.tsx, application/react/Customer/CustomerForm/CustomerForm.tsx, application/react/Die/DieForm/DieForm.tsx, application/react/LinerType/LinerTypeForm/LinerTypeForm.tsx, application/react/Material/MaterialForm/MaterialForm.tsx, application/react/MaterialCategory/MaterialCategoryForm/MaterialCategoryForm.tsx, application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx, application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx, application/react/Vendor/VendorForm/VendorForm.tsx
Previously, when submitting a form, there were cases when form inputs had errors when the user attempted to save the form.
Sometimes, if the form had many inputs, a user might not be able to see the input field's error message and might be confused why the form did not submit. 
This PR adds a message next to the submit button telling them that errors occurred above
=> Add Message Telling Users Form Inputs Had Errors

application/_types/shared/models.ts, application/api/models/material.ts, application/api/services/materialInventoryService.ts, application/react/Inventory/MaterialDetailsModal/MaterialDetailsModal.tsx, application/react/Inventory/Materials/Material/MaterialCard.tsx, application/react/stores/inventoryStore.ts
Currently, we store two models `MaterialLengthAdjustment` and `Material`. A length adjustment relates to a via MaterialLengthAdjustment.material.
We need to regularly figure out how many materialLengthAdjustments relate to any given material. Instead of computing this frequently which will become increasingly expensive, I've decided to add a denormalized field: material.inventory.lengthAdjustments. This field is updated via mongoose hooks to provide quick, cheap, access to the materialLengthAdjustments a material has.
=> Add Denormalized `lengthAdjustments` to DB attribute `material.inventory`

application/react/_global/Table/Row/Row.scss, application/react/_global/Table/Row/Row.tsx, application/react/_global/Table/RowActions/RowActions.scss, application/react/_global/Table/RowActions/RowActions.tsx, application/react/_global/Table/RowHeader/RowHeader.scss, application/react/_global/Table/Table.tsx
I noticed that in edge cases, such as long words in columns that column widths became unaligned.
This PR addresses that, as well as when "row actions" are selected - that popup was popping off the screen.
=> Misc. Table Format Changes

application/_types/shared/models.ts, application/api/controllers/materialLengthAdjustmentController.ts, application/react/Inventory/Materials/Material/MaterialCard.scss, application/react/Inventory/Materials/Material/MaterialCard.tsx, application/react/Inventory/Materials/MaterialCards.tsx, application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx, application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx, application/react/_global/FormInputs/CustomSelect/CustomSelect.scss, application/react/_global/Modal/Modal.scss, application/react/_queries/materialLengthAdjustment.ts
This PR does work on the `MaterialOrder` and `MaterialLengthAdjustment` modals on the Inventory page.
Previously those modals were mostly placeholders, with minimal styling / functionality.
This PR restyles them and adds links for UX purposes
=> Inventory Page Modal Styling

application/api/controllers/materialCategoryController.ts, application/react/Address/AddressForm/AddressForm.tsx, application/react/AdhesiveCategory/AdhesiveCategoryForm/AdhesiveCategoryForm.tsx, application/react/CreditTerm/CreditTermForm/CreditTermForm.tsx, application/react/Customer/Contact/ContactCard/ContactCard.tsx, application/react/Customer/Contact/ContactForm/ContactForm.tsx, application/react/Customer/CustomerForm/CustomerForm.tsx, application/react/DeliveryMethod/DeliveryMethodForm/DeliveryMethodForm.tsx, application/react/Die/DieForm/DieForm.tsx, application/react/LinerType/LinerTypeForm/LinerTypeForm.tsx, application/react/Material/MaterialForm/MaterialForm.tsx, application/react/MaterialCategory/MaterialCategoryForm/MaterialCategoryForm.tsx, application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentForm/MaterialLengthAdjustmentForm.tsx, application/react/MaterialOrder/MaterialOrderForm/MaterialOrderForm.tsx, application/react/Navbars/Navbar/Navbar.tsx, application/react/Product/ProductForm/ProductForm.tsx, application/react/ShippingLocation/ShippingLocationCard/ShippingLocationCard.tsx, application/react/ShippingLocation/ShippingLocationForm/ShippingLocationForm.tsx, application/react/User/Profile/Profile.tsx, application/react/Vendor/VendorForm/VendorForm.tsx, application/react/_auth/ChangePassword/ChangePassword.tsx, application/react/_auth/ForgotPassword/ForgotPassword.tsx, application/react/_auth/Login/Login.tsx, application/react/_auth/Register/Register.tsx, application/react/_global/FilterBar/FilterBar.module.scss, application/react/_global/FormInputs/CustomSelect/CustomSelect.tsx, application/react/_global/FormInputs/Input/Input.tsx, application/react/_global/FormInputs/TextArea/TextArea.tsx
I was creating a feature, where if a Form was loaded, and required input fields were empty, then we needed to style the border of those fields red.
This is easy for "create" forms, but for "update" forms, where data is queried, and then those input fields are dynamically populated (using react-hook-form `reset()`) method. The feature I had built out didn't work.
The fix for this was to wrap every form in a FormProvider (from react-hook-form). Then withinin the `Input` component,  utilize the `useFormContext`.
Now with a context, I no longer needed to prop drill form methods/data into the `Input` component, it was all available in the context. So this PR then made a huge refactor (updates to every form) to remove the prop drilling.
=> Huge Refactor to  Forms

application/react/Inventory/Materials/Material/MaterialCard.module.scss, application/react/Inventory/Materials/Material/MaterialCard.tsx, application/react/_global/FormInputs/CustomSelect/CustomSelect.module.scss, application/react/_global/FormInputs/CustomSelect/CustomSelect.tsx, application/react/_global/FormInputs/Input/Input.module.scss
Continuing push to clean up styles across the UI. This PR was mostly going through random pages and fixing some styling, specifically:
1. Only show action buttons on Material Cards on Inventory page when user hovers
2. Highlight CustomSelect dropdown red, if it's required and a user hasn't made a selection yet
3. Minor Input component style changes
=> Misc style changes

application/api/models/adhesiveCategory.ts, application/react/CreditTerm/CreditTermForm/CreditTermForm.tsx, application/react/CreditTerm/CreditTermTable/CreditTermTable.tsx, cypress/e2e/adhesiveCategory.cy.ts, cypress/e2e/creditTerms.cy.ts, cypress/support/testData.ts, cypress/tsconfig.json, test-utils/cypress/testDataGenerator.ts, test-utils/testDataGenerator.ts, test/models/adhesiveCategory.spec.js, test/models/baseProduct.spec.js, test/models/customer.spec.js, test/models/die.spec.js, test/models/finish.spec.js, test/models/material.spec.js, test/models/newTicket.spec.js, test/models/packingSlip.spec.js, test/models/quote.spec.js, test/models/user.spec.js, test/models/vendor.spec.js, test/services/baseProductService.spec.js, test/services/quoteService.spec.js, test/services/userService.spec.js
This PR adds E2E tests for AdhesiveCategory - specifically around the table and form. More specifically around Creating/Updating/Viewing (Deletion coming eventually)
We also generate randomized data in our unit tests for each of our database entities, including adhesiveCategories - so I migrated that file `testDataGenerator.ts` into a shared folder so both unit tests and cypress can use it. When we get around to really complex entities, I don't realllllly feel like hardcoding 25 different attributes that must match specific validation rules - when all that is already setup and working via the testDataGenerator (thanks past me)
=> `Cypress`: E2E Test `AdhesiveCategory`

application/api/enums/dieNumberPrefixEnum.ts, application/api/index.ts, application/api/models/die.ts, application/react/DeliveryMethod/DeliveryMethodForm/DeliveryMethodForm.tsx, application/react/DeliveryMethod/DeliveryMethodTable/DeliveryMethodTable.tsx, application/react/Die/DieForm/DieForm.tsx, application/react/Die/DieTable/DieTable.tsx, application/react/LinerType/LinerTypeForm/LinerTypeForm.tsx, application/react/LinerType/LinerTypeTable/LinerTypeTable.tsx, application/react/Material/MaterialForm/MaterialForm.tsx, application/react/Material/MaterialTable/MaterialTable.tsx, application/react/_global/FormInputs/CustomSelect/CustomSelect.tsx, application/react/_global/FormInputs/TextArea/TextArea.tsx, cypress/e2e/deliveryMethod.cy.ts, cypress/e2e/die.cy.ts, cypress/e2e/linerType.cy.ts, cypress/e2e/material.cy.ts, cypress/support/commands.ts, cypress/support/seedTestDatabase.ts, cypress/support/testData.ts, test-utils/testDataGenerator.ts, test/models/vendor.spec.js, test/sharedTestDatabase.ts
This PR builds onto the initiative started a PR or so ago, where all the old cypress tests were ripped out, and we're re-buildling them all using an in-memory database, and better technique.
This PR adds cypress tests for the following:
1. DeliveryMethod
2. Die
3. LinerType
4. Material
I also came across many areas of improvement/refactoring while adding these tests. That will likely continue until we're done with these tests. Then I'll come back thru and refactor everyone again. We're on our way 🎊
=> Expand Cypress Test Coverage

application/react/_global/Modal/ConfirmationModal.tsx, cypress/e2e/adhesiveCategory.cy.ts, cypress/e2e/creditTerms.cy.ts, cypress/e2e/customer.cy.ts, cypress/e2e/deliveryMethod.cy.ts, cypress/e2e/die.cy.ts, cypress/e2e/linerType.cy.ts, cypress/e2e/material.cy.ts, cypress/e2e/materialCategory.cy.ts, cypress/e2e/materialLengthAdjustment.cy.ts, cypress/e2e/materialOrder.cy.ts, cypress/e2e/vendor.cy.ts
Currently we have many tables across the UI, used to view Documents of specific types. Each of those tables has an "actions", there should be a "delete" action.
This PR verifies the delete action can be clicked, and a confirmation modal appears before the deletion occurs.
=> `E2E`: Add tests to verify deletions can be performed on every table within the UI 

application/react/_global/Table/Row/Row.module.scss, application/react/_global/Table/RowActions/RowActions.module.scss, application/react/_global/Table/RowHeader/RowHeader.module.scss
I've noticed for a long time that our columns are all the same widths. This includes the last column (the "action") button. The last column doesn't need all this width, so this PR shrinks it to 100px and gives the rest of the columns that width.
I was trying to create a better system for dynamically applying widths to columns, but the effort wasn't worth it, and this system will stay in place (all columns stay the same width) for now.
=> Feat: Minor Tweaks to Table Column Widths

application/react/AdhesiveCategory/AdhesiveCategoryTable/AdhesiveCategoryRowActions/AdhesiveCategoryRowActions.tsx, application/react/CreditTerm/CreditTermTable/CreditTermRowActions/CreditTermRowActions.tsx, application/react/Customer/CustomerTable/CustomerRowActions/CustomerRowActions.tsx, application/react/DeliveryMethod/DeliveryMethodTable/DeliveryMethodRowActions/DeliveryMethodRowActions.tsx, application/react/Die/DieTable/DieRowActions/DieRowActions.tsx, application/react/LinerType/LinerTypeTable/LinerTypeRowActions/LinerTypeRowActions.tsx, application/react/Material/MaterialTable/MaterialRowActions/MaterialRowActions.tsx, application/react/MaterialCategory/MaterialCategoryTable/MaterialCategoryRowActions/MaterialCategoryRowActions.tsx, application/react/MaterialLengthAdjustment/MaterialLengthAdjustmentTable/MaterialLengthAdjustmentRowActions/MaterialLengthAdjustmentRowActions.tsx, application/react/MaterialOrder/MaterialOrderTable/MaterialOrderRowActions/MaterialOrderRowActions.tsx, application/react/Vendor/VendorTable/VendorRowActions/VendorRowActions.tsx, application/react/_global/Modal/ConfirmationModal.tsx, application/react/_global/Modal/useConfirmation.tsx, application/react/_global/Table/TablePageHeader/TablePageHeader.tsx
I noticed when deleting things, that the confirmation modal didn't confirm to the user what exactly they had clicked to delete.
So if they clicked delete on the wrong thing, there was no way they'd know before it was deleted.
After this PR, info, such as the name, of what they clicked delete on are displayed. Eventually I might even have them type this name in the modal - someday.
=> Improve Deletion Modal Text

cypress/e2e/die.cy.ts
Cypress apparently cannot handle typing empty strings. It actually throws an exception and the testing suite fails.
This PR resolves that case.
=> Fix E2E Test

application/api/controllers/adhesiveCategoryController.ts, application/api/controllers/authController.ts, application/api/controllers/creditTermsController.ts, application/api/controllers/customerController.ts, application/api/controllers/deliveryMethodController.ts, application/api/controllers/dieController.ts, application/api/controllers/linerTypeController.ts, application/api/controllers/materialCategoryController.ts, application/api/controllers/materialController.ts, application/api/controllers/materialLengthAdjustmentController.ts, application/api/controllers/materialOrdersController.ts, application/api/controllers/productController.ts, application/api/controllers/quoteController.ts, application/api/controllers/userController.ts, application/api/controllers/vendorController.ts, application/api/enums/httpStatusCodes.ts, application/api/errorHandler.ts, application/api/routes.ts, application/react/_hooks/useErrorMessage.ts
After the recent Express upgrade, the usage of `try { .. } catch() { ... }` in every single express endpoint is no longer a requirement. (Thanks to express v5 finally handling errors that bubble up)
This PR rips out most of the try/catches and replaces them with a global catch-all middleware error handler.
=> Remove Try/Catch's in API and Use Express V5 Global Error Handler Middleware
